// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pintour/v1/booking.proto

package pintourv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Booking status enum
type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_PENDING     BookingStatus = 1
	BookingStatus_BOOKING_STATUS_CONFIRMED   BookingStatus = 2
	BookingStatus_BOOKING_STATUS_CANCELLED   BookingStatus = 3
	BookingStatus_BOOKING_STATUS_COMPLETED   BookingStatus = 4
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_CONFIRMED",
		3: "BOOKING_STATUS_CANCELLED",
		4: "BOOKING_STATUS_COMPLETED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_CONFIRMED":   2,
		"BOOKING_STATUS_CANCELLED":   3,
		"BOOKING_STATUS_COMPLETED":   4,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pintour_v1_booking_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_pintour_v1_booking_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{0}
}

// Booking participant
type BookingParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IdCardNumber  string                 `protobuf:"bytes,3,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingParticipant) Reset() {
	*x = BookingParticipant{}
	mi := &file_pintour_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingParticipant) ProtoMessage() {}

func (x *BookingParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingParticipant.ProtoReflect.Descriptor instead.
func (*BookingParticipant) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *BookingParticipant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookingParticipant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookingParticipant) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *BookingParticipant) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

// Booking
type Booking struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookingCode     string                 `protobuf:"bytes,2,opt,name=booking_code,json=bookingCode,proto3" json:"booking_code,omitempty"`
	UserId          int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourPackageId   int64                  `protobuf:"varint,4,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	TourTitle       string                 `protobuf:"bytes,5,opt,name=tour_title,json=tourTitle,proto3" json:"tour_title,omitempty"`
	TravelDate      string                 `protobuf:"bytes,6,opt,name=travel_date,json=travelDate,proto3" json:"travel_date,omitempty"`
	NumParticipants int32                  `protobuf:"varint,7,opt,name=num_participants,json=numParticipants,proto3" json:"num_participants,omitempty"`
	TotalPrice      float64                `protobuf:"fixed64,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status          BookingStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=pintour.v1.BookingStatus" json:"status,omitempty"`
	Notes           string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	Participants    []*BookingParticipant  `protobuf:"bytes,11,rep,name=participants,proto3" json:"participants,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_pintour_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *Booking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetBookingCode() string {
	if x != nil {
		return x.BookingCode
	}
	return ""
}

func (x *Booking) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *Booking) GetTourTitle() string {
	if x != nil {
		return x.TourTitle
	}
	return ""
}

func (x *Booking) GetTravelDate() string {
	if x != nil {
		return x.TravelDate
	}
	return ""
}

func (x *Booking) GetNumParticipants() int32 {
	if x != nil {
		return x.NumParticipants
	}
	return 0
}

func (x *Booking) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Booking) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *Booking) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Booking) GetParticipants() []*BookingParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Booking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create booking request
type CreateBookingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TourPackageId   int64                  `protobuf:"varint,1,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	TourScheduleId  int64                  `protobuf:"varint,2,opt,name=tour_schedule_id,json=tourScheduleId,proto3" json:"tour_schedule_id,omitempty"`
	TravelDate      string                 `protobuf:"bytes,3,opt,name=travel_date,json=travelDate,proto3" json:"travel_date,omitempty"`
	NumParticipants int32                  `protobuf:"varint,4,opt,name=num_participants,json=numParticipants,proto3" json:"num_participants,omitempty"`
	Notes           string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Participants    []*BookingParticipant  `protobuf:"bytes,6,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_pintour_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookingRequest) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *CreateBookingRequest) GetTourScheduleId() int64 {
	if x != nil {
		return x.TourScheduleId
	}
	return 0
}

func (x *CreateBookingRequest) GetTravelDate() string {
	if x != nil {
		return x.TravelDate
	}
	return ""
}

func (x *CreateBookingRequest) GetNumParticipants() int32 {
	if x != nil {
		return x.NumParticipants
	}
	return 0
}

func (x *CreateBookingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateBookingRequest) GetParticipants() []*BookingParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

// Get booking request
type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_pintour_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// List bookings request (user sees own, admin sees all)
type ListBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        BookingStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=pintour.v1.BookingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_pintour_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *ListBookingsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListBookingsRequest) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

// List bookings response
type ListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_pintour_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ListBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *ListBookingsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Cancel booking request
type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_pintour_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancelBookingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Cancel booking response
type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Booking       *Booking               `protobuf:"bytes,2,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_pintour_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

// Update booking status (admin)
type UpdateBookingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        BookingStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=pintour.v1.BookingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusRequest) Reset() {
	*x = UpdateBookingStatusRequest{}
	mi := &file_pintour_v1_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusRequest) ProtoMessage() {}

func (x *UpdateBookingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_booking_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBookingStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBookingStatusRequest) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

var File_pintour_v1_booking_proto protoreflect.FileDescriptor

const file_pintour_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x18pintour/v1/booking.proto\x12\n" +
	"pintour.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pintour/v1/common.proto\"\x82\x01\n" +
	"\x12BookingParticipant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0eid_card_number\x18\x03 \x01(\tR\fidCardNumber\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\"\x8c\x04\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fbooking_code\x18\x02 \x01(\tR\vbookingCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12&\n" +
	"\x0ftour_package_id\x18\x04 \x01(\x03R\rtourPackageId\x12\x1d\n" +
	"\n" +
	"tour_title\x18\x05 \x01(\tR\ttourTitle\x12\x1f\n" +
	"\vtravel_date\x18\x06 \x01(\tR\n" +
	"travelDate\x12)\n" +
	"\x10num_participants\x18\a \x01(\x05R\x0fnumParticipants\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\x01R\n" +
	"totalPrice\x121\n" +
	"\x06status\x18\t \x01(\x0e2\x19.pintour.v1.BookingStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x12B\n" +
	"\fparticipants\x18\v \x03(\v2\x1e.pintour.v1.BookingParticipantR\fparticipants\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8e\x02\n" +
	"\x14CreateBookingRequest\x12&\n" +
	"\x0ftour_package_id\x18\x01 \x01(\x03R\rtourPackageId\x12(\n" +
	"\x10tour_schedule_id\x18\x02 \x01(\x03R\x0etourScheduleId\x12\x1f\n" +
	"\vtravel_date\x18\x03 \x01(\tR\n" +
	"travelDate\x12)\n" +
	"\x10num_participants\x18\x04 \x01(\x05R\x0fnumParticipants\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12B\n" +
	"\fparticipants\x18\x06 \x03(\v2\x1e.pintour.v1.BookingParticipantR\fparticipants\"#\n" +
	"\x11GetBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x87\x01\n" +
	"\x13ListBookingsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.pintour.v1.PaginationRequestR\n" +
	"pagination\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.pintour.v1.BookingStatusR\x06status\"\x87\x01\n" +
	"\x14ListBookingsResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.pintour.v1.BookingR\bbookings\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.pintour.v1.PaginationResponseR\n" +
	"pagination\">\n" +
	"\x14CancelBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"`\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12-\n" +
	"\abooking\x18\x02 \x01(\v2\x13.pintour.v1.BookingR\abooking\"_\n" +
	"\x1aUpdateBookingStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.pintour.v1.BookingStatusR\x06status*\xa5\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_CONFIRMED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x03\x12\x1c\n" +
	"\x18BOOKING_STATUS_COMPLETED\x10\x042\xe1\x06\n" +
	"\x0eBookingService\x12\x94\x01\n" +
	"\rCreateBooking\x12 .pintour.v1.CreateBookingRequest\x1a\x13.pintour.v1.Booking\"L\x92A2\n" +
	"\bbookings\x12\x14Create a new bookingb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/bookings\x12\x8e\x01\n" +
	"\n" +
	"GetBooking\x12\x1d.pintour.v1.GetBookingRequest\x1a\x13.pintour.v1.Booking\"L\x92A0\n" +
	"\bbookings\x12\x12Get booking detailb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/bookings/{id}\x12\xb5\x01\n" +
	"\fListBookings\x12\x1f.pintour.v1.ListBookingsRequest\x1a .pintour.v1.ListBookingsResponse\"b\x92AK\n" +
	"\bbookings\x12-List bookings (user sees own, admin sees all)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/bookings\x12\xaa\x01\n" +
	"\rCancelBooking\x12 .pintour.v1.CancelBookingRequest\x1a!.pintour.v1.CancelBookingResponse\"T\x92A.\n" +
	"\bbookings\x12\x10Cancel a bookingb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/bookings/{id}/cancel\x12\xc1\x01\n" +
	"\x13UpdateBookingStatus\x12&.pintour.v1.UpdateBookingStatusRequest\x1a\x13.pintour.v1.Booking\"m\x92AA\n" +
	"\x0eadmin-bookings\x12\x1dUpdate booking status (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/v1/admin/bookings/{id}/statusB7Z5github.com/irfan-ghzl/pintour/pb/pintour/v1;pintourv1b\x06proto3"

var (
	file_pintour_v1_booking_proto_rawDescOnce sync.Once
	file_pintour_v1_booking_proto_rawDescData []byte
)

func file_pintour_v1_booking_proto_rawDescGZIP() []byte {
	file_pintour_v1_booking_proto_rawDescOnce.Do(func() {
		file_pintour_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pintour_v1_booking_proto_rawDesc), len(file_pintour_v1_booking_proto_rawDesc)))
	})
	return file_pintour_v1_booking_proto_rawDescData
}

var file_pintour_v1_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pintour_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pintour_v1_booking_proto_goTypes = []any{
	(BookingStatus)(0),                 // 0: pintour.v1.BookingStatus
	(*BookingParticipant)(nil),         // 1: pintour.v1.BookingParticipant
	(*Booking)(nil),                    // 2: pintour.v1.Booking
	(*CreateBookingRequest)(nil),       // 3: pintour.v1.CreateBookingRequest
	(*GetBookingRequest)(nil),          // 4: pintour.v1.GetBookingRequest
	(*ListBookingsRequest)(nil),        // 5: pintour.v1.ListBookingsRequest
	(*ListBookingsResponse)(nil),       // 6: pintour.v1.ListBookingsResponse
	(*CancelBookingRequest)(nil),       // 7: pintour.v1.CancelBookingRequest
	(*CancelBookingResponse)(nil),      // 8: pintour.v1.CancelBookingResponse
	(*UpdateBookingStatusRequest)(nil), // 9: pintour.v1.UpdateBookingStatusRequest
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
	(*PaginationRequest)(nil),          // 11: pintour.v1.PaginationRequest
	(*PaginationResponse)(nil),         // 12: pintour.v1.PaginationResponse
}
var file_pintour_v1_booking_proto_depIdxs = []int32{
	0,  // 0: pintour.v1.Booking.status:type_name -> pintour.v1.BookingStatus
	1,  // 1: pintour.v1.Booking.participants:type_name -> pintour.v1.BookingParticipant
	10, // 2: pintour.v1.Booking.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: pintour.v1.Booking.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: pintour.v1.CreateBookingRequest.participants:type_name -> pintour.v1.BookingParticipant
	11, // 5: pintour.v1.ListBookingsRequest.pagination:type_name -> pintour.v1.PaginationRequest
	0,  // 6: pintour.v1.ListBookingsRequest.status:type_name -> pintour.v1.BookingStatus
	2,  // 7: pintour.v1.ListBookingsResponse.bookings:type_name -> pintour.v1.Booking
	12, // 8: pintour.v1.ListBookingsResponse.pagination:type_name -> pintour.v1.PaginationResponse
	2,  // 9: pintour.v1.CancelBookingResponse.booking:type_name -> pintour.v1.Booking
	0,  // 10: pintour.v1.UpdateBookingStatusRequest.status:type_name -> pintour.v1.BookingStatus
	3,  // 11: pintour.v1.BookingService.CreateBooking:input_type -> pintour.v1.CreateBookingRequest
	4,  // 12: pintour.v1.BookingService.GetBooking:input_type -> pintour.v1.GetBookingRequest
	5,  // 13: pintour.v1.BookingService.ListBookings:input_type -> pintour.v1.ListBookingsRequest
	7,  // 14: pintour.v1.BookingService.CancelBooking:input_type -> pintour.v1.CancelBookingRequest
	9,  // 15: pintour.v1.BookingService.UpdateBookingStatus:input_type -> pintour.v1.UpdateBookingStatusRequest
	2,  // 16: pintour.v1.BookingService.CreateBooking:output_type -> pintour.v1.Booking
	2,  // 17: pintour.v1.BookingService.GetBooking:output_type -> pintour.v1.Booking
	6,  // 18: pintour.v1.BookingService.ListBookings:output_type -> pintour.v1.ListBookingsResponse
	8,  // 19: pintour.v1.BookingService.CancelBooking:output_type -> pintour.v1.CancelBookingResponse
	2,  // 20: pintour.v1.BookingService.UpdateBookingStatus:output_type -> pintour.v1.Booking
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pintour_v1_booking_proto_init() }
func file_pintour_v1_booking_proto_init() {
	if File_pintour_v1_booking_proto != nil {
		return
	}
	file_pintour_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pintour_v1_booking_proto_rawDesc), len(file_pintour_v1_booking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pintour_v1_booking_proto_goTypes,
		DependencyIndexes: file_pintour_v1_booking_proto_depIdxs,
		EnumInfos:         file_pintour_v1_booking_proto_enumTypes,
		MessageInfos:      file_pintour_v1_booking_proto_msgTypes,
	}.Build()
	File_pintour_v1_booking_proto = out.File
	file_pintour_v1_booking_proto_goTypes = nil
	file_pintour_v1_booking_proto_depIdxs = nil
}
