// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pintour/v1/payment.proto

package pintourv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PAID        PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_EXPIRED     PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PAID",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
		5: "PAYMENT_STATUS_EXPIRED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PAID":        2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
		"PAYMENT_STATUS_EXPIRED":     5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pintour_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_pintour_v1_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{0}
}

// Payment method enum
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED   PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD   PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_GOPAY         PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_OVO           PaymentMethod = 4
	PaymentMethod_PAYMENT_METHOD_DANA          PaymentMethod = 5
	PaymentMethod_PAYMENT_METHOD_QRIS          PaymentMethod = 6
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_BANK_TRANSFER",
		2: "PAYMENT_METHOD_CREDIT_CARD",
		3: "PAYMENT_METHOD_GOPAY",
		4: "PAYMENT_METHOD_OVO",
		5: "PAYMENT_METHOD_DANA",
		6: "PAYMENT_METHOD_QRIS",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":   0,
		"PAYMENT_METHOD_BANK_TRANSFER": 1,
		"PAYMENT_METHOD_CREDIT_CARD":   2,
		"PAYMENT_METHOD_GOPAY":         3,
		"PAYMENT_METHOD_OVO":           4,
		"PAYMENT_METHOD_DANA":          5,
		"PAYMENT_METHOD_QRIS":          6,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_pintour_v1_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_pintour_v1_payment_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{1}
}

// Payment
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookingId     int64                  `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BookingCode   string                 `protobuf:"bytes,3,opt,name=booking_code,json=bookingCode,proto3" json:"booking_code,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,4,opt,name=payment_method,json=paymentMethod,proto3,enum=pintour.v1.PaymentMethod" json:"payment_method,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=pintour.v1.PaymentStatus" json:"status,omitempty"`
	PaymentToken  string                 `protobuf:"bytes,7,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,8,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_pintour_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Payment) GetBookingCode() string {
	if x != nil {
		return x.BookingCode
	}
	return ""
}

func (x *Payment) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *Payment) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *Payment) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *Payment) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create payment request
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,2,opt,name=payment_method,json=paymentMethod,proto3,enum=pintour.v1.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_pintour_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CreatePaymentRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

// Create payment response
type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	PaymentToken  string                 `protobuf:"bytes,3,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_pintour_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreatePaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreatePaymentResponse) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

// Get payment request
type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_pintour_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

// Payment notification (webhook from Midtrans)
type PaymentNotificationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TransactionStatus string                 `protobuf:"bytes,2,opt,name=transaction_status,json=transactionStatus,proto3" json:"transaction_status,omitempty"`
	FraudStatus       string                 `protobuf:"bytes,3,opt,name=fraud_status,json=fraudStatus,proto3" json:"fraud_status,omitempty"`
	PaymentType       string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	GrossAmount       string                 `protobuf:"bytes,5,opt,name=gross_amount,json=grossAmount,proto3" json:"gross_amount,omitempty"`
	SignatureKey      string                 `protobuf:"bytes,6,opt,name=signature_key,json=signatureKey,proto3" json:"signature_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentNotificationRequest) Reset() {
	*x = PaymentNotificationRequest{}
	mi := &file_pintour_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentNotificationRequest) ProtoMessage() {}

func (x *PaymentNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentNotificationRequest.ProtoReflect.Descriptor instead.
func (*PaymentNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentNotificationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentNotificationRequest) GetTransactionStatus() string {
	if x != nil {
		return x.TransactionStatus
	}
	return ""
}

func (x *PaymentNotificationRequest) GetFraudStatus() string {
	if x != nil {
		return x.FraudStatus
	}
	return ""
}

func (x *PaymentNotificationRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *PaymentNotificationRequest) GetGrossAmount() string {
	if x != nil {
		return x.GrossAmount
	}
	return ""
}

func (x *PaymentNotificationRequest) GetSignatureKey() string {
	if x != nil {
		return x.SignatureKey
	}
	return ""
}

// Payment notification response
type PaymentNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentNotificationResponse) Reset() {
	*x = PaymentNotificationResponse{}
	mi := &file_pintour_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentNotificationResponse) ProtoMessage() {}

func (x *PaymentNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentNotificationResponse.ProtoReflect.Descriptor instead.
func (*PaymentNotificationResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// List payments (admin)
type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=pintour.v1.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_pintour_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPaymentsRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

// List payments response
type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_pintour_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_pintour_v1_payment_proto protoreflect.FileDescriptor

const file_pintour_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18pintour/v1/payment.proto\x12\n" +
	"pintour.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pintour/v1/common.proto\"\x94\x04\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x03R\tbookingId\x12!\n" +
	"\fbooking_code\x18\x03 \x01(\tR\vbookingCode\x12@\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2\x19.pintour.v1.PaymentMethodR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.pintour.v1.PaymentStatusR\x06status\x12#\n" +
	"\rpayment_token\x18\a \x01(\tR\fpaymentToken\x12\x1f\n" +
	"\vpayment_url\x18\b \x01(\tR\n" +
	"paymentUrl\x123\n" +
	"\apaid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"w\n" +
	"\x14CreatePaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\x12@\n" +
	"\x0epayment_method\x18\x02 \x01(\x0e2\x19.pintour.v1.PaymentMethodR\rpaymentMethod\"\x8c\x01\n" +
	"\x15CreatePaymentResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.pintour.v1.PaymentR\apayment\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\x12#\n" +
	"\rpayment_token\x18\x03 \x01(\tR\fpaymentToken\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\"\xf4\x01\n" +
	"\x1aPaymentNotificationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12-\n" +
	"\x12transaction_status\x18\x02 \x01(\tR\x11transactionStatus\x12!\n" +
	"\ffraud_status\x18\x03 \x01(\tR\vfraudStatus\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x12!\n" +
	"\fgross_amount\x18\x05 \x01(\tR\vgrossAmount\x12#\n" +
	"\rsignature_key\x18\x06 \x01(\tR\fsignatureKey\"7\n" +
	"\x1bPaymentNotificationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x87\x01\n" +
	"\x13ListPaymentsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.pintour.v1.PaginationRequestR\n" +
	"pagination\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.pintour.v1.PaymentStatusR\x06status\"\x87\x01\n" +
	"\x14ListPaymentsResponse\x12/\n" +
	"\bpayments\x18\x01 \x03(\v2\x13.pintour.v1.PaymentR\bpayments\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.pintour.v1.PaginationResponseR\n" +
	"pagination*\xb8\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x04\x12\x1a\n" +
	"\x16PAYMENT_STATUS_EXPIRED\x10\x05*\xd5\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x01\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x02\x12\x18\n" +
	"\x14PAYMENT_METHOD_GOPAY\x10\x03\x12\x16\n" +
	"\x12PAYMENT_METHOD_OVO\x10\x04\x12\x17\n" +
	"\x13PAYMENT_METHOD_DANA\x10\x05\x12\x17\n" +
	"\x13PAYMENT_METHOD_QRIS\x10\x062\xd9\x05\n" +
	"\x0ePaymentService\x12\xaa\x01\n" +
	"\rCreatePayment\x12 .pintour.v1.CreatePaymentRequest\x1a!.pintour.v1.CreatePaymentResponse\"T\x92A:\n" +
	"\bpayments\x12\x1cCreate payment for a bookingb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/payments\x12\xa4\x01\n" +
	"\n" +
	"GetPayment\x12\x1d.pintour.v1.GetPaymentRequest\x1a\x13.pintour.v1.Payment\"b\x92A>\n" +
	"\bpayments\x12 Get payment status for a bookingb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/payments/{booking_id}\x12\xc2\x01\n" +
	"\x13PaymentNotification\x12&.pintour.v1.PaymentNotificationRequest\x1a'.pintour.v1.PaymentNotificationResponse\"Z\x92A3\n" +
	"\bpayments\x12'Payment notification webhook (Midtrans)\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/payments/notification\x12\xad\x01\n" +
	"\fListPayments\x12\x1f.pintour.v1.ListPaymentsRequest\x1a .pintour.v1.ListPaymentsResponse\"Z\x92A=\n" +
	"\x0eadmin-payments\x12\x19List all payments (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/admin/paymentsB7Z5github.com/irfan-ghzl/pintour/pb/pintour/v1;pintourv1b\x06proto3"

var (
	file_pintour_v1_payment_proto_rawDescOnce sync.Once
	file_pintour_v1_payment_proto_rawDescData []byte
)

func file_pintour_v1_payment_proto_rawDescGZIP() []byte {
	file_pintour_v1_payment_proto_rawDescOnce.Do(func() {
		file_pintour_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pintour_v1_payment_proto_rawDesc), len(file_pintour_v1_payment_proto_rawDesc)))
	})
	return file_pintour_v1_payment_proto_rawDescData
}

var file_pintour_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pintour_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pintour_v1_payment_proto_goTypes = []any{
	(PaymentStatus)(0),                  // 0: pintour.v1.PaymentStatus
	(PaymentMethod)(0),                  // 1: pintour.v1.PaymentMethod
	(*Payment)(nil),                     // 2: pintour.v1.Payment
	(*CreatePaymentRequest)(nil),        // 3: pintour.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),       // 4: pintour.v1.CreatePaymentResponse
	(*GetPaymentRequest)(nil),           // 5: pintour.v1.GetPaymentRequest
	(*PaymentNotificationRequest)(nil),  // 6: pintour.v1.PaymentNotificationRequest
	(*PaymentNotificationResponse)(nil), // 7: pintour.v1.PaymentNotificationResponse
	(*ListPaymentsRequest)(nil),         // 8: pintour.v1.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),        // 9: pintour.v1.ListPaymentsResponse
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
	(*PaginationRequest)(nil),           // 11: pintour.v1.PaginationRequest
	(*PaginationResponse)(nil),          // 12: pintour.v1.PaginationResponse
}
var file_pintour_v1_payment_proto_depIdxs = []int32{
	1,  // 0: pintour.v1.Payment.payment_method:type_name -> pintour.v1.PaymentMethod
	0,  // 1: pintour.v1.Payment.status:type_name -> pintour.v1.PaymentStatus
	10, // 2: pintour.v1.Payment.paid_at:type_name -> google.protobuf.Timestamp
	10, // 3: pintour.v1.Payment.expires_at:type_name -> google.protobuf.Timestamp
	10, // 4: pintour.v1.Payment.created_at:type_name -> google.protobuf.Timestamp
	10, // 5: pintour.v1.Payment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: pintour.v1.CreatePaymentRequest.payment_method:type_name -> pintour.v1.PaymentMethod
	2,  // 7: pintour.v1.CreatePaymentResponse.payment:type_name -> pintour.v1.Payment
	11, // 8: pintour.v1.ListPaymentsRequest.pagination:type_name -> pintour.v1.PaginationRequest
	0,  // 9: pintour.v1.ListPaymentsRequest.status:type_name -> pintour.v1.PaymentStatus
	2,  // 10: pintour.v1.ListPaymentsResponse.payments:type_name -> pintour.v1.Payment
	12, // 11: pintour.v1.ListPaymentsResponse.pagination:type_name -> pintour.v1.PaginationResponse
	3,  // 12: pintour.v1.PaymentService.CreatePayment:input_type -> pintour.v1.CreatePaymentRequest
	5,  // 13: pintour.v1.PaymentService.GetPayment:input_type -> pintour.v1.GetPaymentRequest
	6,  // 14: pintour.v1.PaymentService.PaymentNotification:input_type -> pintour.v1.PaymentNotificationRequest
	8,  // 15: pintour.v1.PaymentService.ListPayments:input_type -> pintour.v1.ListPaymentsRequest
	4,  // 16: pintour.v1.PaymentService.CreatePayment:output_type -> pintour.v1.CreatePaymentResponse
	2,  // 17: pintour.v1.PaymentService.GetPayment:output_type -> pintour.v1.Payment
	7,  // 18: pintour.v1.PaymentService.PaymentNotification:output_type -> pintour.v1.PaymentNotificationResponse
	9,  // 19: pintour.v1.PaymentService.ListPayments:output_type -> pintour.v1.ListPaymentsResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pintour_v1_payment_proto_init() }
func file_pintour_v1_payment_proto_init() {
	if File_pintour_v1_payment_proto != nil {
		return
	}
	file_pintour_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pintour_v1_payment_proto_rawDesc), len(file_pintour_v1_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pintour_v1_payment_proto_goTypes,
		DependencyIndexes: file_pintour_v1_payment_proto_depIdxs,
		EnumInfos:         file_pintour_v1_payment_proto_enumTypes,
		MessageInfos:      file_pintour_v1_payment_proto_msgTypes,
	}.Build()
	File_pintour_v1_payment_proto = out.File
	file_pintour_v1_payment_proto_goTypes = nil
	file_pintour_v1_payment_proto_depIdxs = nil
}
