// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pintour/v1/review.proto

package pintourv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Review
type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserAvatar    string                 `protobuf:"bytes,4,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	TourPackageId int64                  `protobuf:"varint,5,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	BookingId     int64                  `protobuf:"varint,6,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Rating        int32                  `protobuf:"varint,7,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_pintour_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_pintour_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Review) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Review) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Review) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *Review) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *Review) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Create review request
type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourPackageId int64                  `protobuf:"varint,1,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	BookingId     int64                  `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_pintour_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRequest) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *CreateReviewRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// List reviews request
type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourPackageId int64                  `protobuf:"varint,1,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_pintour_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *ListReviewsRequest) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *ListReviewsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// List reviews response
type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	AverageRating float64                `protobuf:"fixed64,3,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_pintour_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *ListReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *ListReviewsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListReviewsResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

// Delete review request (admin)
type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_pintour_v1_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_review_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReviewRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Delete review response
type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_pintour_v1_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_review_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReviewResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pintour_v1_review_proto protoreflect.FileDescriptor

const file_pintour_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x17pintour/v1/review.proto\x12\n" +
	"pintour.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pintour/v1/common.proto\"\xa3\x02\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_avatar\x18\x04 \x01(\tR\n" +
	"userAvatar\x12&\n" +
	"\x0ftour_package_id\x18\x05 \x01(\x03R\rtourPackageId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x06 \x01(\x03R\tbookingId\x12\x16\n" +
	"\x06rating\x18\a \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\b \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8e\x01\n" +
	"\x13CreateReviewRequest\x12&\n" +
	"\x0ftour_package_id\x18\x01 \x01(\x03R\rtourPackageId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x03R\tbookingId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"{\n" +
	"\x12ListReviewsRequest\x12&\n" +
	"\x0ftour_package_id\x18\x01 \x01(\x03R\rtourPackageId\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.pintour.v1.PaginationRequestR\n" +
	"pagination\"\xaa\x01\n" +
	"\x13ListReviewsResponse\x12,\n" +
	"\areviews\x18\x01 \x03(\v2\x12.pintour.v1.ReviewR\areviews\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.pintour.v1.PaginationResponseR\n" +
	"pagination\x12%\n" +
	"\x0eaverage_rating\x18\x03 \x01(\x01R\raverageRating\"%\n" +
	"\x13DeleteReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x14DeleteReviewResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x83\x04\n" +
	"\rReviewService\x12\x95\x01\n" +
	"\fCreateReview\x12\x1f.pintour.v1.CreateReviewRequest\x1a\x12.pintour.v1.Review\"P\x92A7\n" +
	"\areviews\x12\x1aCreate a review for a tourb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/reviews\x12\xa8\x01\n" +
	"\vListReviews\x12\x1e.pintour.v1.ListReviewsRequest\x1a\x1f.pintour.v1.ListReviewsResponse\"X\x92A*\n" +
	"\areviews\x12\x1fList reviews for a tour package\x82\xd3\xe4\x93\x02%\x12#/v1/tours/{tour_package_id}/reviews\x12\xae\x01\n" +
	"\fDeleteReview\x12\x1f.pintour.v1.DeleteReviewRequest\x1a .pintour.v1.DeleteReviewResponse\"[\x92A:\n" +
	"\radmin-reviews\x12\x17Delete a review (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18*\x16/v1/admin/reviews/{id}B7Z5github.com/irfan-ghzl/pintour/pb/pintour/v1;pintourv1b\x06proto3"

var (
	file_pintour_v1_review_proto_rawDescOnce sync.Once
	file_pintour_v1_review_proto_rawDescData []byte
)

func file_pintour_v1_review_proto_rawDescGZIP() []byte {
	file_pintour_v1_review_proto_rawDescOnce.Do(func() {
		file_pintour_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pintour_v1_review_proto_rawDesc), len(file_pintour_v1_review_proto_rawDesc)))
	})
	return file_pintour_v1_review_proto_rawDescData
}

var file_pintour_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pintour_v1_review_proto_goTypes = []any{
	(*Review)(nil),                // 0: pintour.v1.Review
	(*CreateReviewRequest)(nil),   // 1: pintour.v1.CreateReviewRequest
	(*ListReviewsRequest)(nil),    // 2: pintour.v1.ListReviewsRequest
	(*ListReviewsResponse)(nil),   // 3: pintour.v1.ListReviewsResponse
	(*DeleteReviewRequest)(nil),   // 4: pintour.v1.DeleteReviewRequest
	(*DeleteReviewResponse)(nil),  // 5: pintour.v1.DeleteReviewResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*PaginationRequest)(nil),     // 7: pintour.v1.PaginationRequest
	(*PaginationResponse)(nil),    // 8: pintour.v1.PaginationResponse
}
var file_pintour_v1_review_proto_depIdxs = []int32{
	6, // 0: pintour.v1.Review.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: pintour.v1.ListReviewsRequest.pagination:type_name -> pintour.v1.PaginationRequest
	0, // 2: pintour.v1.ListReviewsResponse.reviews:type_name -> pintour.v1.Review
	8, // 3: pintour.v1.ListReviewsResponse.pagination:type_name -> pintour.v1.PaginationResponse
	1, // 4: pintour.v1.ReviewService.CreateReview:input_type -> pintour.v1.CreateReviewRequest
	2, // 5: pintour.v1.ReviewService.ListReviews:input_type -> pintour.v1.ListReviewsRequest
	4, // 6: pintour.v1.ReviewService.DeleteReview:input_type -> pintour.v1.DeleteReviewRequest
	0, // 7: pintour.v1.ReviewService.CreateReview:output_type -> pintour.v1.Review
	3, // 8: pintour.v1.ReviewService.ListReviews:output_type -> pintour.v1.ListReviewsResponse
	5, // 9: pintour.v1.ReviewService.DeleteReview:output_type -> pintour.v1.DeleteReviewResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pintour_v1_review_proto_init() }
func file_pintour_v1_review_proto_init() {
	if File_pintour_v1_review_proto != nil {
		return
	}
	file_pintour_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pintour_v1_review_proto_rawDesc), len(file_pintour_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pintour_v1_review_proto_goTypes,
		DependencyIndexes: file_pintour_v1_review_proto_depIdxs,
		MessageInfos:      file_pintour_v1_review_proto_msgTypes,
	}.Build()
	File_pintour_v1_review_proto = out.File
	file_pintour_v1_review_proto_goTypes = nil
	file_pintour_v1_review_proto_depIdxs = nil
}
