// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pintour/v1/tour.proto

package pintourv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourService_ListTourPackages_FullMethodName   = "/pintour.v1.TourService/ListTourPackages"
	TourService_GetTourPackage_FullMethodName     = "/pintour.v1.TourService/GetTourPackage"
	TourService_CreateTourPackage_FullMethodName  = "/pintour.v1.TourService/CreateTourPackage"
	TourService_UpdateTourPackage_FullMethodName  = "/pintour.v1.TourService/UpdateTourPackage"
	TourService_DeleteTourPackage_FullMethodName  = "/pintour.v1.TourService/DeleteTourPackage"
	TourService_ListDestinations_FullMethodName   = "/pintour.v1.TourService/ListDestinations"
	TourService_CreateDestination_FullMethodName  = "/pintour.v1.TourService/CreateDestination"
	TourService_ListTourSchedules_FullMethodName  = "/pintour.v1.TourService/ListTourSchedules"
	TourService_CreateTourSchedule_FullMethodName = "/pintour.v1.TourService/CreateTourSchedule"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tour service
type TourServiceClient interface {
	ListTourPackages(ctx context.Context, in *ListTourPackagesRequest, opts ...grpc.CallOption) (*ListTourPackagesResponse, error)
	GetTourPackage(ctx context.Context, in *GetTourPackageRequest, opts ...grpc.CallOption) (*TourPackage, error)
	CreateTourPackage(ctx context.Context, in *CreateTourPackageRequest, opts ...grpc.CallOption) (*TourPackage, error)
	UpdateTourPackage(ctx context.Context, in *UpdateTourPackageRequest, opts ...grpc.CallOption) (*TourPackage, error)
	DeleteTourPackage(ctx context.Context, in *DeleteTourPackageRequest, opts ...grpc.CallOption) (*DeleteTourPackageResponse, error)
	ListDestinations(ctx context.Context, in *ListDestinationsRequest, opts ...grpc.CallOption) (*ListDestinationsResponse, error)
	CreateDestination(ctx context.Context, in *CreateDestinationRequest, opts ...grpc.CallOption) (*Destination, error)
	ListTourSchedules(ctx context.Context, in *ListTourSchedulesRequest, opts ...grpc.CallOption) (*ListTourSchedulesResponse, error)
	CreateTourSchedule(ctx context.Context, in *CreateTourScheduleRequest, opts ...grpc.CallOption) (*TourSchedule, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) ListTourPackages(ctx context.Context, in *ListTourPackagesRequest, opts ...grpc.CallOption) (*ListTourPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTourPackagesResponse)
	err := c.cc.Invoke(ctx, TourService_ListTourPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTourPackage(ctx context.Context, in *GetTourPackageRequest, opts ...grpc.CallOption) (*TourPackage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourPackage)
	err := c.cc.Invoke(ctx, TourService_GetTourPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateTourPackage(ctx context.Context, in *CreateTourPackageRequest, opts ...grpc.CallOption) (*TourPackage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourPackage)
	err := c.cc.Invoke(ctx, TourService_CreateTourPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) UpdateTourPackage(ctx context.Context, in *UpdateTourPackageRequest, opts ...grpc.CallOption) (*TourPackage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourPackage)
	err := c.cc.Invoke(ctx, TourService_UpdateTourPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) DeleteTourPackage(ctx context.Context, in *DeleteTourPackageRequest, opts ...grpc.CallOption) (*DeleteTourPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTourPackageResponse)
	err := c.cc.Invoke(ctx, TourService_DeleteTourPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) ListDestinations(ctx context.Context, in *ListDestinationsRequest, opts ...grpc.CallOption) (*ListDestinationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDestinationsResponse)
	err := c.cc.Invoke(ctx, TourService_ListDestinations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateDestination(ctx context.Context, in *CreateDestinationRequest, opts ...grpc.CallOption) (*Destination, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Destination)
	err := c.cc.Invoke(ctx, TourService_CreateDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) ListTourSchedules(ctx context.Context, in *ListTourSchedulesRequest, opts ...grpc.CallOption) (*ListTourSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTourSchedulesResponse)
	err := c.cc.Invoke(ctx, TourService_ListTourSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateTourSchedule(ctx context.Context, in *CreateTourScheduleRequest, opts ...grpc.CallOption) (*TourSchedule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourSchedule)
	err := c.cc.Invoke(ctx, TourService_CreateTourSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility.
//
// Tour service
type TourServiceServer interface {
	ListTourPackages(context.Context, *ListTourPackagesRequest) (*ListTourPackagesResponse, error)
	GetTourPackage(context.Context, *GetTourPackageRequest) (*TourPackage, error)
	CreateTourPackage(context.Context, *CreateTourPackageRequest) (*TourPackage, error)
	UpdateTourPackage(context.Context, *UpdateTourPackageRequest) (*TourPackage, error)
	DeleteTourPackage(context.Context, *DeleteTourPackageRequest) (*DeleteTourPackageResponse, error)
	ListDestinations(context.Context, *ListDestinationsRequest) (*ListDestinationsResponse, error)
	CreateDestination(context.Context, *CreateDestinationRequest) (*Destination, error)
	ListTourSchedules(context.Context, *ListTourSchedulesRequest) (*ListTourSchedulesResponse, error)
	CreateTourSchedule(context.Context, *CreateTourScheduleRequest) (*TourSchedule, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourServiceServer struct{}

func (UnimplementedTourServiceServer) ListTourPackages(context.Context, *ListTourPackagesRequest) (*ListTourPackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTourPackages not implemented")
}
func (UnimplementedTourServiceServer) GetTourPackage(context.Context, *GetTourPackageRequest) (*TourPackage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTourPackage not implemented")
}
func (UnimplementedTourServiceServer) CreateTourPackage(context.Context, *CreateTourPackageRequest) (*TourPackage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTourPackage not implemented")
}
func (UnimplementedTourServiceServer) UpdateTourPackage(context.Context, *UpdateTourPackageRequest) (*TourPackage, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTourPackage not implemented")
}
func (UnimplementedTourServiceServer) DeleteTourPackage(context.Context, *DeleteTourPackageRequest) (*DeleteTourPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTourPackage not implemented")
}
func (UnimplementedTourServiceServer) ListDestinations(context.Context, *ListDestinationsRequest) (*ListDestinationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDestinations not implemented")
}
func (UnimplementedTourServiceServer) CreateDestination(context.Context, *CreateDestinationRequest) (*Destination, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDestination not implemented")
}
func (UnimplementedTourServiceServer) ListTourSchedules(context.Context, *ListTourSchedulesRequest) (*ListTourSchedulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTourSchedules not implemented")
}
func (UnimplementedTourServiceServer) CreateTourSchedule(context.Context, *CreateTourScheduleRequest) (*TourSchedule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTourSchedule not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}
func (UnimplementedTourServiceServer) testEmbeddedByValue()                     {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	// If the following call panics, it indicates UnimplementedTourServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_ListTourPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTourPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).ListTourPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_ListTourPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).ListTourPackages(ctx, req.(*ListTourPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTourPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTourPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourPackage(ctx, req.(*GetTourPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateTourPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateTourPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateTourPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateTourPackage(ctx, req.(*CreateTourPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_UpdateTourPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTourPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).UpdateTourPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_UpdateTourPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).UpdateTourPackage(ctx, req.(*UpdateTourPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_DeleteTourPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTourPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).DeleteTourPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_DeleteTourPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).DeleteTourPackage(ctx, req.(*DeleteTourPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_ListDestinations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDestinationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).ListDestinations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_ListDestinations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).ListDestinations(ctx, req.(*ListDestinationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateDestination(ctx, req.(*CreateDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_ListTourSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTourSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).ListTourSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_ListTourSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).ListTourSchedules(ctx, req.(*ListTourSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateTourSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateTourSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateTourSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateTourSchedule(ctx, req.(*CreateTourScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pintour.v1.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTourPackages",
			Handler:    _TourService_ListTourPackages_Handler,
		},
		{
			MethodName: "GetTourPackage",
			Handler:    _TourService_GetTourPackage_Handler,
		},
		{
			MethodName: "CreateTourPackage",
			Handler:    _TourService_CreateTourPackage_Handler,
		},
		{
			MethodName: "UpdateTourPackage",
			Handler:    _TourService_UpdateTourPackage_Handler,
		},
		{
			MethodName: "DeleteTourPackage",
			Handler:    _TourService_DeleteTourPackage_Handler,
		},
		{
			MethodName: "ListDestinations",
			Handler:    _TourService_ListDestinations_Handler,
		},
		{
			MethodName: "CreateDestination",
			Handler:    _TourService_CreateDestination_Handler,
		},
		{
			MethodName: "ListTourSchedules",
			Handler:    _TourService_ListTourSchedules_Handler,
		},
		{
			MethodName: "CreateTourSchedule",
			Handler:    _TourService_CreateTourSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pintour/v1/tour.proto",
}
