// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pintour/v1/tour.proto

package pintourv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tour category enum
type TourCategory int32

const (
	TourCategory_TOUR_CATEGORY_UNSPECIFIED TourCategory = 0
	TourCategory_TOUR_CATEGORY_ADVENTURE   TourCategory = 1
	TourCategory_TOUR_CATEGORY_CULTURAL    TourCategory = 2
	TourCategory_TOUR_CATEGORY_BEACH       TourCategory = 3
	TourCategory_TOUR_CATEGORY_CITY        TourCategory = 4
	TourCategory_TOUR_CATEGORY_NATURE      TourCategory = 5
	TourCategory_TOUR_CATEGORY_RELIGIOUS   TourCategory = 6
	TourCategory_TOUR_CATEGORY_HONEYMOON   TourCategory = 7
	TourCategory_TOUR_CATEGORY_FAMILY      TourCategory = 8
)

// Enum value maps for TourCategory.
var (
	TourCategory_name = map[int32]string{
		0: "TOUR_CATEGORY_UNSPECIFIED",
		1: "TOUR_CATEGORY_ADVENTURE",
		2: "TOUR_CATEGORY_CULTURAL",
		3: "TOUR_CATEGORY_BEACH",
		4: "TOUR_CATEGORY_CITY",
		5: "TOUR_CATEGORY_NATURE",
		6: "TOUR_CATEGORY_RELIGIOUS",
		7: "TOUR_CATEGORY_HONEYMOON",
		8: "TOUR_CATEGORY_FAMILY",
	}
	TourCategory_value = map[string]int32{
		"TOUR_CATEGORY_UNSPECIFIED": 0,
		"TOUR_CATEGORY_ADVENTURE":   1,
		"TOUR_CATEGORY_CULTURAL":    2,
		"TOUR_CATEGORY_BEACH":       3,
		"TOUR_CATEGORY_CITY":        4,
		"TOUR_CATEGORY_NATURE":      5,
		"TOUR_CATEGORY_RELIGIOUS":   6,
		"TOUR_CATEGORY_HONEYMOON":   7,
		"TOUR_CATEGORY_FAMILY":      8,
	}
)

func (x TourCategory) Enum() *TourCategory {
	p := new(TourCategory)
	*p = x
	return p
}

func (x TourCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pintour_v1_tour_proto_enumTypes[0].Descriptor()
}

func (TourCategory) Type() protoreflect.EnumType {
	return &file_pintour_v1_tour_proto_enumTypes[0]
}

func (x TourCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourCategory.Descriptor instead.
func (TourCategory) EnumDescriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{0}
}

// Destination
type Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_pintour_v1_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{0}
}

func (x *Destination) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Destination) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Destination) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Destination) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Destination) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Destination) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Destination) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Tour itinerary
type TourItinerary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DayNumber     int32                  `protobuf:"varint,2,opt,name=day_number,json=dayNumber,proto3" json:"day_number,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourItinerary) Reset() {
	*x = TourItinerary{}
	mi := &file_pintour_v1_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourItinerary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourItinerary) ProtoMessage() {}

func (x *TourItinerary) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourItinerary.ProtoReflect.Descriptor instead.
func (*TourItinerary) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{1}
}

func (x *TourItinerary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourItinerary) GetDayNumber() int32 {
	if x != nil {
		return x.DayNumber
	}
	return 0
}

func (x *TourItinerary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TourItinerary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Tour facility
type TourFacility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourFacility) Reset() {
	*x = TourFacility{}
	mi := &file_pintour_v1_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourFacility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourFacility) ProtoMessage() {}

func (x *TourFacility) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourFacility.ProtoReflect.Descriptor instead.
func (*TourFacility) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{2}
}

func (x *TourFacility) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourFacility) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Tour package
type TourPackage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Destination     *Destination           `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Price           float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DurationDays    int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,7,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	MinParticipants int32                  `protobuf:"varint,8,opt,name=min_participants,json=minParticipants,proto3" json:"min_participants,omitempty"`
	Category        TourCategory           `protobuf:"varint,9,opt,name=category,proto3,enum=pintour.v1.TourCategory" json:"category,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsActive        bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	AverageRating   float64                `protobuf:"fixed64,12,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	ReviewCount     int32                  `protobuf:"varint,13,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	Itineraries     []*TourItinerary       `protobuf:"bytes,14,rep,name=itineraries,proto3" json:"itineraries,omitempty"`
	Facilities      []*TourFacility        `protobuf:"bytes,15,rep,name=facilities,proto3" json:"facilities,omitempty"`
	Images          []string               `protobuf:"bytes,16,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TourPackage) Reset() {
	*x = TourPackage{}
	mi := &file_pintour_v1_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourPackage) ProtoMessage() {}

func (x *TourPackage) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourPackage.ProtoReflect.Descriptor instead.
func (*TourPackage) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{3}
}

func (x *TourPackage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourPackage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TourPackage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourPackage) GetDestination() *Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *TourPackage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourPackage) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *TourPackage) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *TourPackage) GetMinParticipants() int32 {
	if x != nil {
		return x.MinParticipants
	}
	return 0
}

func (x *TourPackage) GetCategory() TourCategory {
	if x != nil {
		return x.Category
	}
	return TourCategory_TOUR_CATEGORY_UNSPECIFIED
}

func (x *TourPackage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TourPackage) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TourPackage) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *TourPackage) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *TourPackage) GetItineraries() []*TourItinerary {
	if x != nil {
		return x.Itineraries
	}
	return nil
}

func (x *TourPackage) GetFacilities() []*TourFacility {
	if x != nil {
		return x.Facilities
	}
	return nil
}

func (x *TourPackage) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *TourPackage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TourPackage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Tour schedule
type TourSchedule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TourPackageId  int64                  `protobuf:"varint,2,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	StartDate      string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AvailableSlots int32                  `protobuf:"varint,5,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TourSchedule) Reset() {
	*x = TourSchedule{}
	mi := &file_pintour_v1_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourSchedule) ProtoMessage() {}

func (x *TourSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourSchedule.ProtoReflect.Descriptor instead.
func (*TourSchedule) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{4}
}

func (x *TourSchedule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourSchedule) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *TourSchedule) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TourSchedule) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TourSchedule) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *TourSchedule) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourSchedule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// List tour packages request
type ListTourPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Category      TourCategory           `protobuf:"varint,3,opt,name=category,proto3,enum=pintour.v1.TourCategory" json:"category,omitempty"`
	DestinationId int64                  `protobuf:"varint,4,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	MinDuration   int32                  `protobuf:"varint,7,opt,name=min_duration,json=minDuration,proto3" json:"min_duration,omitempty"`
	MaxDuration   int32                  `protobuf:"varint,8,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTourPackagesRequest) Reset() {
	*x = ListTourPackagesRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTourPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTourPackagesRequest) ProtoMessage() {}

func (x *ListTourPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTourPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListTourPackagesRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{5}
}

func (x *ListTourPackagesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTourPackagesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListTourPackagesRequest) GetCategory() TourCategory {
	if x != nil {
		return x.Category
	}
	return TourCategory_TOUR_CATEGORY_UNSPECIFIED
}

func (x *ListTourPackagesRequest) GetDestinationId() int64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

func (x *ListTourPackagesRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListTourPackagesRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListTourPackagesRequest) GetMinDuration() int32 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *ListTourPackagesRequest) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

// List tour packages response
type ListTourPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*TourPackage         `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTourPackagesResponse) Reset() {
	*x = ListTourPackagesResponse{}
	mi := &file_pintour_v1_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTourPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTourPackagesResponse) ProtoMessage() {}

func (x *ListTourPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTourPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListTourPackagesResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{6}
}

func (x *ListTourPackagesResponse) GetPackages() []*TourPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *ListTourPackagesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Get tour package request
type GetTourPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourPackageRequest) Reset() {
	*x = GetTourPackageRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourPackageRequest) ProtoMessage() {}

func (x *GetTourPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourPackageRequest.ProtoReflect.Descriptor instead.
func (*GetTourPackageRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{7}
}

func (x *GetTourPackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Create tour package request (admin)
type CreateTourPackageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DestinationId   int64                  `protobuf:"varint,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Price           float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	DurationDays    int32                  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,6,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	MinParticipants int32                  `protobuf:"varint,7,opt,name=min_participants,json=minParticipants,proto3" json:"min_participants,omitempty"`
	Category        TourCategory           `protobuf:"varint,8,opt,name=category,proto3,enum=pintour.v1.TourCategory" json:"category,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTourPackageRequest) Reset() {
	*x = CreateTourPackageRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourPackageRequest) ProtoMessage() {}

func (x *CreateTourPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourPackageRequest.ProtoReflect.Descriptor instead.
func (*CreateTourPackageRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTourPackageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTourPackageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourPackageRequest) GetDestinationId() int64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

func (x *CreateTourPackageRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTourPackageRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CreateTourPackageRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *CreateTourPackageRequest) GetMinParticipants() int32 {
	if x != nil {
		return x.MinParticipants
	}
	return 0
}

func (x *CreateTourPackageRequest) GetCategory() TourCategory {
	if x != nil {
		return x.Category
	}
	return TourCategory_TOUR_CATEGORY_UNSPECIFIED
}

func (x *CreateTourPackageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// Update tour package request (admin)
type UpdateTourPackageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price           float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	DurationDays    int32                  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,6,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	MinParticipants int32                  `protobuf:"varint,7,opt,name=min_participants,json=minParticipants,proto3" json:"min_participants,omitempty"`
	Category        TourCategory           `protobuf:"varint,8,opt,name=category,proto3,enum=pintour.v1.TourCategory" json:"category,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsActive        bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTourPackageRequest) Reset() {
	*x = UpdateTourPackageRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourPackageRequest) ProtoMessage() {}

func (x *UpdateTourPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourPackageRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourPackageRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTourPackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTourPackageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTourPackageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTourPackageRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTourPackageRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpdateTourPackageRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *UpdateTourPackageRequest) GetMinParticipants() int32 {
	if x != nil {
		return x.MinParticipants
	}
	return 0
}

func (x *UpdateTourPackageRequest) GetCategory() TourCategory {
	if x != nil {
		return x.Category
	}
	return TourCategory_TOUR_CATEGORY_UNSPECIFIED
}

func (x *UpdateTourPackageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateTourPackageRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// Delete tour package request (admin)
type DeleteTourPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTourPackageRequest) Reset() {
	*x = DeleteTourPackageRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTourPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTourPackageRequest) ProtoMessage() {}

func (x *DeleteTourPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTourPackageRequest.ProtoReflect.Descriptor instead.
func (*DeleteTourPackageRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTourPackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Delete tour package response
type DeleteTourPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTourPackageResponse) Reset() {
	*x = DeleteTourPackageResponse{}
	mi := &file_pintour_v1_tour_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTourPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTourPackageResponse) ProtoMessage() {}

func (x *DeleteTourPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTourPackageResponse.ProtoReflect.Descriptor instead.
func (*DeleteTourPackageResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTourPackageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// List destinations request
type ListDestinationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDestinationsRequest) Reset() {
	*x = ListDestinationsRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDestinationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDestinationsRequest) ProtoMessage() {}

func (x *ListDestinationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDestinationsRequest.ProtoReflect.Descriptor instead.
func (*ListDestinationsRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{12}
}

func (x *ListDestinationsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListDestinationsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListDestinationsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// List destinations response
type ListDestinationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destinations  []*Destination         `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDestinationsResponse) Reset() {
	*x = ListDestinationsResponse{}
	mi := &file_pintour_v1_tour_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDestinationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDestinationsResponse) ProtoMessage() {}

func (x *ListDestinationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDestinationsResponse.ProtoReflect.Descriptor instead.
func (*ListDestinationsResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{13}
}

func (x *ListDestinationsResponse) GetDestinations() []*Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *ListDestinationsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Create destination request (admin)
type CreateDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDestinationRequest) Reset() {
	*x = CreateDestinationRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDestinationRequest) ProtoMessage() {}

func (x *CreateDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDestinationRequest.ProtoReflect.Descriptor instead.
func (*CreateDestinationRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{14}
}

func (x *CreateDestinationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDestinationRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateDestinationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateDestinationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDestinationRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// List tour schedules request
type ListTourSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourPackageId int64                  `protobuf:"varint,1,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTourSchedulesRequest) Reset() {
	*x = ListTourSchedulesRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTourSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTourSchedulesRequest) ProtoMessage() {}

func (x *ListTourSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTourSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListTourSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{15}
}

func (x *ListTourSchedulesRequest) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *ListTourSchedulesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListTourSchedulesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// List tour schedules response
type ListTourSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*TourSchedule        `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTourSchedulesResponse) Reset() {
	*x = ListTourSchedulesResponse{}
	mi := &file_pintour_v1_tour_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTourSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTourSchedulesResponse) ProtoMessage() {}

func (x *ListTourSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTourSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListTourSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{16}
}

func (x *ListTourSchedulesResponse) GetSchedules() []*TourSchedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

// Create tour schedule request (admin)
type CreateTourScheduleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TourPackageId  int64                  `protobuf:"varint,1,opt,name=tour_package_id,json=tourPackageId,proto3" json:"tour_package_id,omitempty"`
	StartDate      string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AvailableSlots int32                  `protobuf:"varint,4,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTourScheduleRequest) Reset() {
	*x = CreateTourScheduleRequest{}
	mi := &file_pintour_v1_tour_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourScheduleRequest) ProtoMessage() {}

func (x *CreateTourScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pintour_v1_tour_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateTourScheduleRequest) Descriptor() ([]byte, []int) {
	return file_pintour_v1_tour_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTourScheduleRequest) GetTourPackageId() int64 {
	if x != nil {
		return x.TourPackageId
	}
	return 0
}

func (x *CreateTourScheduleRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateTourScheduleRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateTourScheduleRequest) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

var File_pintour_v1_tour_proto protoreflect.FileDescriptor

const file_pintour_v1_tour_proto_rawDesc = "" +
	"\n" +
	"\x15pintour/v1/tour.proto\x12\n" +
	"pintour.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pintour/v1/common.proto\"\xd9\x01\n" +
	"\vDestination\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"v\n" +
	"\rTourItinerary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"day_number\x18\x02 \x01(\x05R\tdayNumber\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"2\n" +
	"\fTourFacility\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe0\x05\n" +
	"\vTourPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\vdestination\x18\x04 \x01(\v2\x17.pintour.v1.DestinationR\vdestination\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\x12)\n" +
	"\x10max_participants\x18\a \x01(\x05R\x0fmaxParticipants\x12)\n" +
	"\x10min_participants\x18\b \x01(\x05R\x0fminParticipants\x124\n" +
	"\bcategory\x18\t \x01(\x0e2\x18.pintour.v1.TourCategoryR\bcategory\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12%\n" +
	"\x0eaverage_rating\x18\f \x01(\x01R\raverageRating\x12!\n" +
	"\freview_count\x18\r \x01(\x05R\vreviewCount\x12;\n" +
	"\vitineraries\x18\x0e \x03(\v2\x19.pintour.v1.TourItineraryR\vitineraries\x128\n" +
	"\n" +
	"facilities\x18\x0f \x03(\v2\x18.pintour.v1.TourFacilityR\n" +
	"facilities\x12\x16\n" +
	"\x06images\x18\x10 \x03(\tR\x06images\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfc\x01\n" +
	"\fTourSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0ftour_package_id\x18\x02 \x01(\x03R\rtourPackageId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12'\n" +
	"\x0favailable_slots\x18\x05 \x01(\x05R\x0eavailableSlots\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcd\x02\n" +
	"\x17ListTourPackagesRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.pintour.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x124\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x18.pintour.v1.TourCategoryR\bcategory\x12%\n" +
	"\x0edestination_id\x18\x04 \x01(\x03R\rdestinationId\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x01R\bmaxPrice\x12!\n" +
	"\fmin_duration\x18\a \x01(\x05R\vminDuration\x12!\n" +
	"\fmax_duration\x18\b \x01(\x05R\vmaxDuration\"\x8f\x01\n" +
	"\x18ListTourPackagesResponse\x123\n" +
	"\bpackages\x18\x01 \x03(\v2\x17.pintour.v1.TourPackageR\bpackages\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.pintour.v1.PaginationResponseR\n" +
	"pagination\"'\n" +
	"\x15GetTourPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xdd\x02\n" +
	"\x18CreateTourPackageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\x0edestination_id\x18\x03 \x01(\x03R\rdestinationId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12#\n" +
	"\rduration_days\x18\x05 \x01(\x05R\fdurationDays\x12)\n" +
	"\x10max_participants\x18\x06 \x01(\x05R\x0fmaxParticipants\x12)\n" +
	"\x10min_participants\x18\a \x01(\x05R\x0fminParticipants\x124\n" +
	"\bcategory\x18\b \x01(\x0e2\x18.pintour.v1.TourCategoryR\bcategory\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\"\xe3\x02\n" +
	"\x18UpdateTourPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12#\n" +
	"\rduration_days\x18\x05 \x01(\x05R\fdurationDays\x12)\n" +
	"\x10max_participants\x18\x06 \x01(\x05R\x0fmaxParticipants\x12)\n" +
	"\x10min_participants\x18\a \x01(\x05R\x0fminParticipants\x124\n" +
	"\bcategory\x18\b \x01(\x0e2\x18.pintour.v1.TourCategoryR\bcategory\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"*\n" +
	"\x18DeleteTourPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x19DeleteTourPackageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8a\x01\n" +
	"\x17ListDestinationsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.pintour.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"\x97\x01\n" +
	"\x18ListDestinationsResponse\x12;\n" +
	"\fdestinations\x18\x01 \x03(\v2\x17.pintour.v1.DestinationR\fdestinations\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.pintour.v1.PaginationResponseR\n" +
	"pagination\"\x9b\x01\n" +
	"\x18CreateDestinationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\"|\n" +
	"\x18ListTourSchedulesRequest\x12&\n" +
	"\x0ftour_package_id\x18\x01 \x01(\x03R\rtourPackageId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"S\n" +
	"\x19ListTourSchedulesResponse\x126\n" +
	"\tschedules\x18\x01 \x03(\v2\x18.pintour.v1.TourScheduleR\tschedules\"\xa6\x01\n" +
	"\x19CreateTourScheduleRequest\x12&\n" +
	"\x0ftour_package_id\x18\x01 \x01(\x03R\rtourPackageId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12'\n" +
	"\x0favailable_slots\x18\x04 \x01(\x05R\x0eavailableSlots*\x85\x02\n" +
	"\fTourCategory\x12\x1d\n" +
	"\x19TOUR_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TOUR_CATEGORY_ADVENTURE\x10\x01\x12\x1a\n" +
	"\x16TOUR_CATEGORY_CULTURAL\x10\x02\x12\x17\n" +
	"\x13TOUR_CATEGORY_BEACH\x10\x03\x12\x16\n" +
	"\x12TOUR_CATEGORY_CITY\x10\x04\x12\x18\n" +
	"\x14TOUR_CATEGORY_NATURE\x10\x05\x12\x1b\n" +
	"\x17TOUR_CATEGORY_RELIGIOUS\x10\x06\x12\x1b\n" +
	"\x17TOUR_CATEGORY_HONEYMOON\x10\a\x12\x18\n" +
	"\x14TOUR_CATEGORY_FAMILY\x10\b2\xa9\f\n" +
	"\vTourService\x12\x8e\x01\n" +
	"\x10ListTourPackages\x12#.pintour.v1.ListTourPackagesRequest\x1a$.pintour.v1.ListTourPackagesResponse\"/\x92A\x1b\n" +
	"\x05tours\x12\x12List tour packages\x82\xd3\xe4\x93\x02\v\x12\t/v1/tours\x12\x87\x01\n" +
	"\x0eGetTourPackage\x12!.pintour.v1.GetTourPackageRequest\x1a\x17.pintour.v1.TourPackage\"9\x92A \n" +
	"\x05tours\x12\x17Get tour package detail\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/tours/{id}\x12\xad\x01\n" +
	"\x11CreateTourPackage\x12$.pintour.v1.CreateTourPackageRequest\x1a\x17.pintour.v1.TourPackage\"Y\x92A<\n" +
	"\vadmin-tours\x12\x1bCreate tour package (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/admin/tours\x12\xb2\x01\n" +
	"\x11UpdateTourPackage\x12$.pintour.v1.UpdateTourPackageRequest\x1a\x17.pintour.v1.TourPackage\"^\x92A<\n" +
	"\vadmin-tours\x12\x1bUpdate tour package (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/v1/admin/tours/{id}\x12\xbd\x01\n" +
	"\x11DeleteTourPackage\x12$.pintour.v1.DeleteTourPackageRequest\x1a%.pintour.v1.DeleteTourPackageResponse\"[\x92A<\n" +
	"\vadmin-tours\x12\x1bDelete tour package (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x16*\x14/v1/admin/tours/{id}\x12\x9b\x01\n" +
	"\x10ListDestinations\x12#.pintour.v1.ListDestinationsRequest\x1a$.pintour.v1.ListDestinationsResponse\"<\x92A!\n" +
	"\fdestinations\x12\x11List destinations\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/destinations\x12\xba\x01\n" +
	"\x11CreateDestination\x12$.pintour.v1.CreateDestinationRequest\x1a\x17.pintour.v1.Destination\"f\x92AB\n" +
	"\x12admin-destinations\x12\x1aCreate destination (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/admin/destinations\x12\xae\x01\n" +
	"\x11ListTourSchedules\x12$.pintour.v1.ListTourSchedulesRequest\x1a%.pintour.v1.ListTourSchedulesResponse\"L\x92A\x1c\n" +
	"\x05tours\x12\x13List tour schedules\x82\xd3\xe4\x93\x02'\x12%/v1/tours/{tour_package_id}/schedules\x12\xcd\x01\n" +
	"\x12CreateTourSchedule\x12%.pintour.v1.CreateTourScheduleRequest\x1a\x18.pintour.v1.TourSchedule\"v\x92A=\n" +
	"\vadmin-tours\x12\x1cCreate tour schedule (admin)b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x020:\x01*\"+/v1/admin/tours/{tour_package_id}/schedulesB7Z5github.com/irfan-ghzl/pintour/pb/pintour/v1;pintourv1b\x06proto3"

var (
	file_pintour_v1_tour_proto_rawDescOnce sync.Once
	file_pintour_v1_tour_proto_rawDescData []byte
)

func file_pintour_v1_tour_proto_rawDescGZIP() []byte {
	file_pintour_v1_tour_proto_rawDescOnce.Do(func() {
		file_pintour_v1_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pintour_v1_tour_proto_rawDesc), len(file_pintour_v1_tour_proto_rawDesc)))
	})
	return file_pintour_v1_tour_proto_rawDescData
}

var file_pintour_v1_tour_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pintour_v1_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pintour_v1_tour_proto_goTypes = []any{
	(TourCategory)(0),                 // 0: pintour.v1.TourCategory
	(*Destination)(nil),               // 1: pintour.v1.Destination
	(*TourItinerary)(nil),             // 2: pintour.v1.TourItinerary
	(*TourFacility)(nil),              // 3: pintour.v1.TourFacility
	(*TourPackage)(nil),               // 4: pintour.v1.TourPackage
	(*TourSchedule)(nil),              // 5: pintour.v1.TourSchedule
	(*ListTourPackagesRequest)(nil),   // 6: pintour.v1.ListTourPackagesRequest
	(*ListTourPackagesResponse)(nil),  // 7: pintour.v1.ListTourPackagesResponse
	(*GetTourPackageRequest)(nil),     // 8: pintour.v1.GetTourPackageRequest
	(*CreateTourPackageRequest)(nil),  // 9: pintour.v1.CreateTourPackageRequest
	(*UpdateTourPackageRequest)(nil),  // 10: pintour.v1.UpdateTourPackageRequest
	(*DeleteTourPackageRequest)(nil),  // 11: pintour.v1.DeleteTourPackageRequest
	(*DeleteTourPackageResponse)(nil), // 12: pintour.v1.DeleteTourPackageResponse
	(*ListDestinationsRequest)(nil),   // 13: pintour.v1.ListDestinationsRequest
	(*ListDestinationsResponse)(nil),  // 14: pintour.v1.ListDestinationsResponse
	(*CreateDestinationRequest)(nil),  // 15: pintour.v1.CreateDestinationRequest
	(*ListTourSchedulesRequest)(nil),  // 16: pintour.v1.ListTourSchedulesRequest
	(*ListTourSchedulesResponse)(nil), // 17: pintour.v1.ListTourSchedulesResponse
	(*CreateTourScheduleRequest)(nil), // 18: pintour.v1.CreateTourScheduleRequest
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
	(*PaginationRequest)(nil),         // 20: pintour.v1.PaginationRequest
	(*PaginationResponse)(nil),        // 21: pintour.v1.PaginationResponse
}
var file_pintour_v1_tour_proto_depIdxs = []int32{
	19, // 0: pintour.v1.Destination.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: pintour.v1.TourPackage.destination:type_name -> pintour.v1.Destination
	0,  // 2: pintour.v1.TourPackage.category:type_name -> pintour.v1.TourCategory
	2,  // 3: pintour.v1.TourPackage.itineraries:type_name -> pintour.v1.TourItinerary
	3,  // 4: pintour.v1.TourPackage.facilities:type_name -> pintour.v1.TourFacility
	19, // 5: pintour.v1.TourPackage.created_at:type_name -> google.protobuf.Timestamp
	19, // 6: pintour.v1.TourPackage.updated_at:type_name -> google.protobuf.Timestamp
	19, // 7: pintour.v1.TourSchedule.created_at:type_name -> google.protobuf.Timestamp
	20, // 8: pintour.v1.ListTourPackagesRequest.pagination:type_name -> pintour.v1.PaginationRequest
	0,  // 9: pintour.v1.ListTourPackagesRequest.category:type_name -> pintour.v1.TourCategory
	4,  // 10: pintour.v1.ListTourPackagesResponse.packages:type_name -> pintour.v1.TourPackage
	21, // 11: pintour.v1.ListTourPackagesResponse.pagination:type_name -> pintour.v1.PaginationResponse
	0,  // 12: pintour.v1.CreateTourPackageRequest.category:type_name -> pintour.v1.TourCategory
	0,  // 13: pintour.v1.UpdateTourPackageRequest.category:type_name -> pintour.v1.TourCategory
	20, // 14: pintour.v1.ListDestinationsRequest.pagination:type_name -> pintour.v1.PaginationRequest
	1,  // 15: pintour.v1.ListDestinationsResponse.destinations:type_name -> pintour.v1.Destination
	21, // 16: pintour.v1.ListDestinationsResponse.pagination:type_name -> pintour.v1.PaginationResponse
	5,  // 17: pintour.v1.ListTourSchedulesResponse.schedules:type_name -> pintour.v1.TourSchedule
	6,  // 18: pintour.v1.TourService.ListTourPackages:input_type -> pintour.v1.ListTourPackagesRequest
	8,  // 19: pintour.v1.TourService.GetTourPackage:input_type -> pintour.v1.GetTourPackageRequest
	9,  // 20: pintour.v1.TourService.CreateTourPackage:input_type -> pintour.v1.CreateTourPackageRequest
	10, // 21: pintour.v1.TourService.UpdateTourPackage:input_type -> pintour.v1.UpdateTourPackageRequest
	11, // 22: pintour.v1.TourService.DeleteTourPackage:input_type -> pintour.v1.DeleteTourPackageRequest
	13, // 23: pintour.v1.TourService.ListDestinations:input_type -> pintour.v1.ListDestinationsRequest
	15, // 24: pintour.v1.TourService.CreateDestination:input_type -> pintour.v1.CreateDestinationRequest
	16, // 25: pintour.v1.TourService.ListTourSchedules:input_type -> pintour.v1.ListTourSchedulesRequest
	18, // 26: pintour.v1.TourService.CreateTourSchedule:input_type -> pintour.v1.CreateTourScheduleRequest
	7,  // 27: pintour.v1.TourService.ListTourPackages:output_type -> pintour.v1.ListTourPackagesResponse
	4,  // 28: pintour.v1.TourService.GetTourPackage:output_type -> pintour.v1.TourPackage
	4,  // 29: pintour.v1.TourService.CreateTourPackage:output_type -> pintour.v1.TourPackage
	4,  // 30: pintour.v1.TourService.UpdateTourPackage:output_type -> pintour.v1.TourPackage
	12, // 31: pintour.v1.TourService.DeleteTourPackage:output_type -> pintour.v1.DeleteTourPackageResponse
	14, // 32: pintour.v1.TourService.ListDestinations:output_type -> pintour.v1.ListDestinationsResponse
	1,  // 33: pintour.v1.TourService.CreateDestination:output_type -> pintour.v1.Destination
	17, // 34: pintour.v1.TourService.ListTourSchedules:output_type -> pintour.v1.ListTourSchedulesResponse
	5,  // 35: pintour.v1.TourService.CreateTourSchedule:output_type -> pintour.v1.TourSchedule
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pintour_v1_tour_proto_init() }
func file_pintour_v1_tour_proto_init() {
	if File_pintour_v1_tour_proto != nil {
		return
	}
	file_pintour_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pintour_v1_tour_proto_rawDesc), len(file_pintour_v1_tour_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pintour_v1_tour_proto_goTypes,
		DependencyIndexes: file_pintour_v1_tour_proto_depIdxs,
		EnumInfos:         file_pintour_v1_tour_proto_enumTypes,
		MessageInfos:      file_pintour_v1_tour_proto_msgTypes,
	}.Build()
	File_pintour_v1_tour_proto = out.File
	file_pintour_v1_tour_proto_goTypes = nil
	file_pintour_v1_tour_proto_depIdxs = nil
}
