// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: destinations.sql

package db

import (
	"context"
	"database/sql"
)

const countDestinations = `-- name: CountDestinations :one
SELECT COUNT(*) FROM destinations
WHERE
  ($1::text = '' OR name ILIKE '%' || $1 || '%' OR country ILIKE '%' || $1 || '%' OR city ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR country = $2)
`

type CountDestinationsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountDestinations(ctx context.Context, arg CountDestinationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDestinations, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (
  name, country, city, description, image_url
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, country, city, description, image_url, created_at, updated_at
`

type CreateDestinationParams struct {
	Name        string `json:"name"`
	Country     string `json:"country"`
	City        string `json:"city"`
	Description string `json:"description"`
	ImageUrl    string `json:"image_url"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRowContext(ctx, createDestination,
		arg.Name,
		arg.Country,
		arg.City,
		arg.Description,
		arg.ImageUrl,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.City,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDestination = `-- name: GetDestination :one
SELECT id, name, country, city, description, image_url, created_at, updated_at FROM destinations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDestination(ctx context.Context, id int64) (Destination, error) {
	row := q.db.QueryRowContext(ctx, getDestination, id)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.City,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDestinations = `-- name: ListDestinations :many
SELECT id, name, country, city, description, image_url, created_at, updated_at FROM destinations
WHERE
  ($1::text = '' OR name ILIKE '%' || $1 || '%' OR country ILIKE '%' || $1 || '%' OR city ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR country = $2)
ORDER BY name
LIMIT $3 OFFSET $4
`

type ListDestinationsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListDestinations(ctx context.Context, arg ListDestinationsParams) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, listDestinations,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Destination{}
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.City,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :one
UPDATE destinations
SET
  name = COALESCE($2, name),
  country = COALESCE($3, country),
  city = COALESCE($4, city),
  description = COALESCE($5, description),
  image_url = COALESCE($6, image_url),
  updated_at = now()
WHERE id = $1
RETURNING id, name, country, city, description, image_url, created_at, updated_at
`

type UpdateDestinationParams struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Country     sql.NullString `json:"country"`
	City        sql.NullString `json:"city"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (Destination, error) {
	row := q.db.QueryRowContext(ctx, updateDestination,
		arg.ID,
		arg.Name,
		arg.Country,
		arg.City,
		arg.Description,
		arg.ImageUrl,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.City,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
