// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockSession(ctx context.Context, id uuid.UUID) (Session, error)
	CountAllBookings(ctx context.Context, dollar_1 string) (int64, error)
	CountBookingsByUser(ctx context.Context, arg CountBookingsByUserParams) (int64, error)
	CountDestinations(ctx context.Context, arg CountDestinationsParams) (int64, error)
	CountPayments(ctx context.Context, dollar_1 string) (int64, error)
	CountReviewsByTour(ctx context.Context, tourPackageID int64) (int64, error)
	CountTourPackages(ctx context.Context, arg CountTourPackagesParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBookingParticipant(ctx context.Context, arg CreateBookingParticipantParams) (BookingParticipant, error)
	CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTourFacility(ctx context.Context, arg CreateTourFacilityParams) (TourFacility, error)
	CreateTourImage(ctx context.Context, arg CreateTourImageParams) (TourImage, error)
	CreateTourItinerary(ctx context.Context, arg CreateTourItineraryParams) (TourItinerary, error)
	CreateTourPackage(ctx context.Context, arg CreateTourPackageParams) (TourPackage, error)
	CreateTourSchedule(ctx context.Context, arg CreateTourScheduleParams) (TourSchedule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteReview(ctx context.Context, id int64) error
	DeleteTourPackage(ctx context.Context, id int64) error
	GetAverageRating(ctx context.Context, tourPackageID int64) (string, error)
	GetBooking(ctx context.Context, id int64) (Booking, error)
	GetBookingByCode(ctx context.Context, bookingCode string) (Booking, error)
	GetDestination(ctx context.Context, id int64) (Destination, error)
	GetPaymentByBookingID(ctx context.Context, bookingID int64) (Payment, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetReview(ctx context.Context, id int64) (Review, error)
	GetReviewByBooking(ctx context.Context, arg GetReviewByBookingParams) (Review, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTourPackage(ctx context.Context, id int64) (TourPackage, error)
	GetTourSchedule(ctx context.Context, id int64) (TourSchedule, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListAllBookings(ctx context.Context, arg ListAllBookingsParams) ([]Booking, error)
	ListBookingParticipants(ctx context.Context, bookingID int64) ([]BookingParticipant, error)
	ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]Booking, error)
	ListDestinations(ctx context.Context, arg ListDestinationsParams) ([]Destination, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListReviewsByTour(ctx context.Context, arg ListReviewsByTourParams) ([]ListReviewsByTourRow, error)
	ListTourFacilities(ctx context.Context, tourPackageID int64) ([]TourFacility, error)
	ListTourImages(ctx context.Context, tourPackageID int64) ([]TourImage, error)
	ListTourItineraries(ctx context.Context, tourPackageID int64) ([]TourItinerary, error)
	ListTourPackages(ctx context.Context, arg ListTourPackagesParams) ([]TourPackage, error)
	ListTourSchedules(ctx context.Context, arg ListTourSchedulesParams) ([]TourSchedule, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (Destination, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePaymentToken(ctx context.Context, arg UpdatePaymentTokenParams) (Payment, error)
	UpdateTourPackage(ctx context.Context, arg UpdateTourPackageParams) (TourPackage, error)
	UpdateTourScheduleSlots(ctx context.Context, arg UpdateTourScheduleSlotsParams) (TourSchedule, error)
	UpdateTourScheduleStatus(ctx context.Context, arg UpdateTourScheduleStatusParams) (TourSchedule, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserVerified(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
