// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_schedules.sql

package db

import (
	"context"
	"time"
)

const createTourSchedule = `-- name: CreateTourSchedule :one
INSERT INTO tour_schedules (
  tour_package_id, start_date, end_date, available_slots
) VALUES (
  $1, $2, $3, $4
) RETURNING id, tour_package_id, start_date, end_date, available_slots, status, created_at, updated_at
`

type CreateTourScheduleParams struct {
	TourPackageID  int64     `json:"tour_package_id"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
	AvailableSlots int32     `json:"available_slots"`
}

func (q *Queries) CreateTourSchedule(ctx context.Context, arg CreateTourScheduleParams) (TourSchedule, error) {
	row := q.db.QueryRowContext(ctx, createTourSchedule,
		arg.TourPackageID,
		arg.StartDate,
		arg.EndDate,
		arg.AvailableSlots,
	)
	var i TourSchedule
	err := row.Scan(
		&i.ID,
		&i.TourPackageID,
		&i.StartDate,
		&i.EndDate,
		&i.AvailableSlots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTourSchedule = `-- name: GetTourSchedule :one
SELECT id, tour_package_id, start_date, end_date, available_slots, status, created_at, updated_at FROM tour_schedules
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTourSchedule(ctx context.Context, id int64) (TourSchedule, error) {
	row := q.db.QueryRowContext(ctx, getTourSchedule, id)
	var i TourSchedule
	err := row.Scan(
		&i.ID,
		&i.TourPackageID,
		&i.StartDate,
		&i.EndDate,
		&i.AvailableSlots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTourSchedules = `-- name: ListTourSchedules :many
SELECT id, tour_package_id, start_date, end_date, available_slots, status, created_at, updated_at FROM tour_schedules
WHERE
  tour_package_id = $1
  AND ($2::date = '0001-01-01' OR start_date >= $2)
  AND ($3::date = '0001-01-01' OR end_date <= $3)
ORDER BY start_date
`

type ListTourSchedulesParams struct {
	TourPackageID int64     `json:"tour_package_id"`
	Column2       time.Time `json:"column_2"`
	Column3       time.Time `json:"column_3"`
}

func (q *Queries) ListTourSchedules(ctx context.Context, arg ListTourSchedulesParams) ([]TourSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listTourSchedules, arg.TourPackageID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourSchedule{}
	for rows.Next() {
		var i TourSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TourPackageID,
			&i.StartDate,
			&i.EndDate,
			&i.AvailableSlots,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTourScheduleSlots = `-- name: UpdateTourScheduleSlots :one
UPDATE tour_schedules
SET available_slots = available_slots - $2, updated_at = now()
WHERE id = $1 AND available_slots >= $2
RETURNING id, tour_package_id, start_date, end_date, available_slots, status, created_at, updated_at
`

type UpdateTourScheduleSlotsParams struct {
	ID             int64 `json:"id"`
	AvailableSlots int32 `json:"available_slots"`
}

func (q *Queries) UpdateTourScheduleSlots(ctx context.Context, arg UpdateTourScheduleSlotsParams) (TourSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateTourScheduleSlots, arg.ID, arg.AvailableSlots)
	var i TourSchedule
	err := row.Scan(
		&i.ID,
		&i.TourPackageID,
		&i.StartDate,
		&i.EndDate,
		&i.AvailableSlots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTourScheduleStatus = `-- name: UpdateTourScheduleStatus :one
UPDATE tour_schedules
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, tour_package_id, start_date, end_date, available_slots, status, created_at, updated_at
`

type UpdateTourScheduleStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTourScheduleStatus(ctx context.Context, arg UpdateTourScheduleStatusParams) (TourSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateTourScheduleStatus, arg.ID, arg.Status)
	var i TourSchedule
	err := row.Scan(
		&i.ID,
		&i.TourPackageID,
		&i.StartDate,
		&i.EndDate,
		&i.AvailableSlots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
