// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, name, phone, password_hash, google_id, avatar_url, role
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email, name, phone, password_hash, google_id, avatar_url, role, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	Phone        string `json:"phone"`
	PasswordHash string `json:"password_hash"`
	GoogleID     string `json:"google_id"`
	AvatarUrl    string `json:"avatar_url"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.PasswordHash,
		arg.GoogleID,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, phone, password_hash, google_id, avatar_url, role, is_verified, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, name, phone, password_hash, google_id, avatar_url, role, is_verified, created_at, updated_at FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, phone, password_hash, google_id, avatar_url, role, is_verified, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, phone, password_hash, google_id, avatar_url, role, is_verified, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Phone,
			&i.PasswordHash,
			&i.GoogleID,
			&i.AvatarUrl,
			&i.Role,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  name = COALESCE($2, name),
  phone = COALESCE($3, phone),
  avatar_url = COALESCE($4, avatar_url),
  updated_at = now()
WHERE id = $1
RETURNING id, email, name, phone, password_hash, google_id, avatar_url, role, is_verified, created_at, updated_at
`

type UpdateUserParams struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Phone     sql.NullString `json:"phone"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVerified = `-- name: UpdateUserVerified :one
UPDATE users
SET is_verified = true, updated_at = now()
WHERE id = $1
RETURNING id, email, name, phone, password_hash, google_id, avatar_url, role, is_verified, created_at, updated_at
`

func (q *Queries) UpdateUserVerified(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
