// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAllBookings = `-- name: CountAllBookings :one
SELECT COUNT(*) FROM bookings
WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountAllBookings(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllBookings, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByUser = `-- name: CountBookingsByUser :one
SELECT COUNT(*) FROM bookings
WHERE
  user_id = $1
  AND ($2::text = '' OR status = $2)
`

type CountBookingsByUserParams struct {
	UserID  int64  `json:"user_id"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountBookingsByUser(ctx context.Context, arg CountBookingsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookingsByUser, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  booking_code, user_id, tour_package_id, tour_schedule_id,
  travel_date, num_participants, total_price, notes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, booking_code, user_id, tour_package_id, tour_schedule_id, travel_date, num_participants, total_price, status, notes, created_at, updated_at
`

type CreateBookingParams struct {
	BookingCode     string        `json:"booking_code"`
	UserID          int64         `json:"user_id"`
	TourPackageID   int64         `json:"tour_package_id"`
	TourScheduleID  sql.NullInt64 `json:"tour_schedule_id"`
	TravelDate      time.Time     `json:"travel_date"`
	NumParticipants int32         `json:"num_participants"`
	TotalPrice      string        `json:"total_price"`
	Notes           string        `json:"notes"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.BookingCode,
		arg.UserID,
		arg.TourPackageID,
		arg.TourScheduleID,
		arg.TravelDate,
		arg.NumParticipants,
		arg.TotalPrice,
		arg.Notes,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.TourPackageID,
		&i.TourScheduleID,
		&i.TravelDate,
		&i.NumParticipants,
		&i.TotalPrice,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingParticipant = `-- name: CreateBookingParticipant :one
INSERT INTO booking_participants (
  booking_id, name, id_card_number, date_of_birth
) VALUES (
  $1, $2, $3, $4
) RETURNING id, booking_id, name, id_card_number, date_of_birth, created_at
`

type CreateBookingParticipantParams struct {
	BookingID    int64        `json:"booking_id"`
	Name         string       `json:"name"`
	IDCardNumber string       `json:"id_card_number"`
	DateOfBirth  sql.NullTime `json:"date_of_birth"`
}

func (q *Queries) CreateBookingParticipant(ctx context.Context, arg CreateBookingParticipantParams) (BookingParticipant, error) {
	row := q.db.QueryRowContext(ctx, createBookingParticipant,
		arg.BookingID,
		arg.Name,
		arg.IDCardNumber,
		arg.DateOfBirth,
	)
	var i BookingParticipant
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Name,
		&i.IDCardNumber,
		&i.DateOfBirth,
		&i.CreatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, booking_code, user_id, tour_package_id, tour_schedule_id, travel_date, num_participants, total_price, status, notes, created_at, updated_at FROM bookings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBooking(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.TourPackageID,
		&i.TourScheduleID,
		&i.TravelDate,
		&i.NumParticipants,
		&i.TotalPrice,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByCode = `-- name: GetBookingByCode :one
SELECT id, booking_code, user_id, tour_package_id, tour_schedule_id, travel_date, num_participants, total_price, status, notes, created_at, updated_at FROM bookings
WHERE booking_code = $1 LIMIT 1
`

func (q *Queries) GetBookingByCode(ctx context.Context, bookingCode string) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByCode, bookingCode)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.TourPackageID,
		&i.TourScheduleID,
		&i.TravelDate,
		&i.NumParticipants,
		&i.TotalPrice,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllBookings = `-- name: ListAllBookings :many
SELECT id, booking_code, user_id, tour_package_id, tour_schedule_id, travel_date, num_participants, total_price, status, notes, created_at, updated_at FROM bookings
WHERE ($1::text = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllBookingsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAllBookings(ctx context.Context, arg ListAllBookingsParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listAllBookings, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.BookingCode,
			&i.UserID,
			&i.TourPackageID,
			&i.TourScheduleID,
			&i.TravelDate,
			&i.NumParticipants,
			&i.TotalPrice,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingParticipants = `-- name: ListBookingParticipants :many
SELECT id, booking_id, name, id_card_number, date_of_birth, created_at FROM booking_participants
WHERE booking_id = $1
`

func (q *Queries) ListBookingParticipants(ctx context.Context, bookingID int64) ([]BookingParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listBookingParticipants, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingParticipant{}
	for rows.Next() {
		var i BookingParticipant
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Name,
			&i.IDCardNumber,
			&i.DateOfBirth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, booking_code, user_id, tour_package_id, tour_schedule_id, travel_date, num_participants, total_price, status, notes, created_at, updated_at FROM bookings
WHERE
  user_id = $1
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListBookingsByUserParams struct {
	UserID  int64  `json:"user_id"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByUser,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.BookingCode,
			&i.UserID,
			&i.TourPackageID,
			&i.TourScheduleID,
			&i.TravelDate,
			&i.NumParticipants,
			&i.TotalPrice,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, booking_code, user_id, tour_package_id, tour_schedule_id, travel_date, num_participants, total_price, status, notes, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.TourPackageID,
		&i.TourScheduleID,
		&i.TravelDate,
		&i.NumParticipants,
		&i.TotalPrice,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
