// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID              int64         `json:"id"`
	BookingCode     string        `json:"booking_code"`
	UserID          int64         `json:"user_id"`
	TourPackageID   int64         `json:"tour_package_id"`
	TourScheduleID  sql.NullInt64 `json:"tour_schedule_id"`
	TravelDate      time.Time     `json:"travel_date"`
	NumParticipants int32         `json:"num_participants"`
	TotalPrice      string        `json:"total_price"`
	Status          string        `json:"status"`
	Notes           string        `json:"notes"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type BookingParticipant struct {
	ID           int64        `json:"id"`
	BookingID    int64        `json:"booking_id"`
	Name         string       `json:"name"`
	IDCardNumber string       `json:"id_card_number"`
	DateOfBirth  sql.NullTime `json:"date_of_birth"`
	CreatedAt    time.Time    `json:"created_at"`
}

type Destination struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Country     string    `json:"country"`
	City        string    `json:"city"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Payment struct {
	ID            int64        `json:"id"`
	BookingID     int64        `json:"booking_id"`
	PaymentMethod string       `json:"payment_method"`
	Amount        string       `json:"amount"`
	Status        string       `json:"status"`
	PaymentToken  string       `json:"payment_token"`
	PaymentUrl    string       `json:"payment_url"`
	PaidAt        sql.NullTime `json:"paid_at"`
	ExpiresAt     sql.NullTime `json:"expires_at"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

type Review struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	TourPackageID int64     `json:"tour_package_id"`
	BookingID     int64     `json:"booking_id"`
	Rating        int32     `json:"rating"`
	Comment       string    `json:"comment"`
	CreatedAt     time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type TourFacility struct {
	ID            int64     `json:"id"`
	TourPackageID int64     `json:"tour_package_id"`
	Name          string    `json:"name"`
	CreatedAt     time.Time `json:"created_at"`
}

type TourImage struct {
	ID            int64     `json:"id"`
	TourPackageID int64     `json:"tour_package_id"`
	ImageUrl      string    `json:"image_url"`
	CreatedAt     time.Time `json:"created_at"`
}

type TourItinerary struct {
	ID            int64     `json:"id"`
	TourPackageID int64     `json:"tour_package_id"`
	DayNumber     int32     `json:"day_number"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	CreatedAt     time.Time `json:"created_at"`
}

type TourPackage struct {
	ID              int64     `json:"id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	DestinationID   int64     `json:"destination_id"`
	Price           string    `json:"price"`
	DurationDays    int32     `json:"duration_days"`
	MaxParticipants int32     `json:"max_participants"`
	MinParticipants int32     `json:"min_participants"`
	Category        string    `json:"category"`
	ImageUrl        string    `json:"image_url"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type TourSchedule struct {
	ID             int64     `json:"id"`
	TourPackageID  int64     `json:"tour_package_id"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
	AvailableSlots int32     `json:"available_slots"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Phone        string    `json:"phone"`
	PasswordHash string    `json:"password_hash"`
	GoogleID     string    `json:"google_id"`
	AvatarUrl    string    `json:"avatar_url"`
	Role         string    `json:"role"`
	IsVerified   bool      `json:"is_verified"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
