// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) FROM payments
WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountPayments(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPayments, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  booking_id, payment_method, amount, status, payment_token, payment_url, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, booking_id, payment_method, amount, status, payment_token, payment_url, paid_at, expires_at, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID     int64        `json:"booking_id"`
	PaymentMethod string       `json:"payment_method"`
	Amount        string       `json:"amount"`
	Status        string       `json:"status"`
	PaymentToken  string       `json:"payment_token"`
	PaymentUrl    string       `json:"payment_url"`
	ExpiresAt     sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.BookingID,
		arg.PaymentMethod,
		arg.Amount,
		arg.Status,
		arg.PaymentToken,
		arg.PaymentUrl,
		arg.ExpiresAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.PaymentToken,
		&i.PaymentUrl,
		&i.PaidAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByBookingID = `-- name: GetPaymentByBookingID :one
SELECT id, booking_id, payment_method, amount, status, payment_token, payment_url, paid_at, expires_at, created_at, updated_at FROM payments
WHERE booking_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByBookingID(ctx context.Context, bookingID int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByBookingID, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.PaymentToken,
		&i.PaymentUrl,
		&i.PaidAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, booking_id, payment_method, amount, status, payment_token, payment_url, paid_at, expires_at, created_at, updated_at FROM payments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.PaymentToken,
		&i.PaymentUrl,
		&i.PaidAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, booking_id, payment_method, amount, status, payment_token, payment_url, paid_at, expires_at, created_at, updated_at FROM payments
WHERE ($1::text = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.PaymentMethod,
			&i.Amount,
			&i.Status,
			&i.PaymentToken,
			&i.PaymentUrl,
			&i.PaidAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET
  status = $2,
  paid_at = CASE WHEN $2 = 'paid' THEN now() ELSE paid_at END,
  updated_at = now()
WHERE id = $1
RETURNING id, booking_id, payment_method, amount, status, payment_token, payment_url, paid_at, expires_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.PaymentToken,
		&i.PaymentUrl,
		&i.PaidAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentToken = `-- name: UpdatePaymentToken :one
UPDATE payments
SET
  payment_token = $2,
  payment_url = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, booking_id, payment_method, amount, status, payment_token, payment_url, paid_at, expires_at, created_at, updated_at
`

type UpdatePaymentTokenParams struct {
	ID           int64  `json:"id"`
	PaymentToken string `json:"payment_token"`
	PaymentUrl   string `json:"payment_url"`
}

func (q *Queries) UpdatePaymentToken(ctx context.Context, arg UpdatePaymentTokenParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentToken, arg.ID, arg.PaymentToken, arg.PaymentUrl)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.PaymentToken,
		&i.PaymentUrl,
		&i.PaidAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
