// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package db

import (
	"context"
	"time"
)

const countReviewsByTour = `-- name: CountReviewsByTour :one
SELECT COUNT(*) FROM reviews
WHERE tour_package_id = $1
`

func (q *Queries) CountReviewsByTour(ctx context.Context, tourPackageID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsByTour, tourPackageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
  user_id, tour_package_id, booking_id, rating, comment
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, user_id, tour_package_id, booking_id, rating, comment, created_at
`

type CreateReviewParams struct {
	UserID        int64  `json:"user_id"`
	TourPackageID int64  `json:"tour_package_id"`
	BookingID     int64  `json:"booking_id"`
	Rating        int32  `json:"rating"`
	Comment       string `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.UserID,
		arg.TourPackageID,
		arg.BookingID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TourPackageID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const getAverageRating = `-- name: GetAverageRating :one
SELECT COALESCE(AVG(rating), 0)::decimal(3,2) as average_rating
FROM reviews
WHERE tour_package_id = $1
`

func (q *Queries) GetAverageRating(ctx context.Context, tourPackageID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getAverageRating, tourPackageID)
	var average_rating string
	err := row.Scan(&average_rating)
	return average_rating, err
}

const getReview = `-- name: GetReview :one
SELECT id, user_id, tour_package_id, booking_id, rating, comment, created_at FROM reviews
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TourPackageID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByBooking = `-- name: GetReviewByBooking :one
SELECT id, user_id, tour_package_id, booking_id, rating, comment, created_at FROM reviews
WHERE user_id = $1 AND booking_id = $2 LIMIT 1
`

type GetReviewByBookingParams struct {
	UserID    int64 `json:"user_id"`
	BookingID int64 `json:"booking_id"`
}

func (q *Queries) GetReviewByBooking(ctx context.Context, arg GetReviewByBookingParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByBooking, arg.UserID, arg.BookingID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TourPackageID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listReviewsByTour = `-- name: ListReviewsByTour :many
SELECT r.id, r.user_id, r.tour_package_id, r.booking_id, r.rating, r.comment, r.created_at, u.name as user_name, u.avatar_url as user_avatar
FROM reviews r
JOIN users u ON r.user_id = u.id
WHERE r.tour_package_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByTourParams struct {
	TourPackageID int64 `json:"tour_package_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

type ListReviewsByTourRow struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	TourPackageID int64     `json:"tour_package_id"`
	BookingID     int64     `json:"booking_id"`
	Rating        int32     `json:"rating"`
	Comment       string    `json:"comment"`
	CreatedAt     time.Time `json:"created_at"`
	UserName      string    `json:"user_name"`
	UserAvatar    string    `json:"user_avatar"`
}

func (q *Queries) ListReviewsByTour(ctx context.Context, arg ListReviewsByTourParams) ([]ListReviewsByTourRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByTour, arg.TourPackageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByTourRow{}
	for rows.Next() {
		var i ListReviewsByTourRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TourPackageID,
			&i.BookingID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UserName,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
