// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_packages.sql

package db

import (
	"context"
	"database/sql"
)

const countTourPackages = `-- name: CountTourPackages :one
SELECT COUNT(*) FROM tour_packages tp
WHERE
  tp.is_active = true
  AND ($1::text = '' OR tp.title ILIKE '%' || $1 || '%' OR tp.description ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR tp.category = $2)
  AND ($3::bigint = 0 OR tp.destination_id = $3)
  AND ($4::decimal = 0 OR tp.price >= $4)
  AND ($5::decimal = 0 OR tp.price <= $5)
`

type CountTourPackagesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 int64  `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
}

func (q *Queries) CountTourPackages(ctx context.Context, arg CountTourPackagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTourPackages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTourFacility = `-- name: CreateTourFacility :one
INSERT INTO tour_facilities (tour_package_id, name)
VALUES ($1, $2)
RETURNING id, tour_package_id, name, created_at
`

type CreateTourFacilityParams struct {
	TourPackageID int64  `json:"tour_package_id"`
	Name          string `json:"name"`
}

func (q *Queries) CreateTourFacility(ctx context.Context, arg CreateTourFacilityParams) (TourFacility, error) {
	row := q.db.QueryRowContext(ctx, createTourFacility, arg.TourPackageID, arg.Name)
	var i TourFacility
	err := row.Scan(
		&i.ID,
		&i.TourPackageID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createTourImage = `-- name: CreateTourImage :one
INSERT INTO tour_images (tour_package_id, image_url)
VALUES ($1, $2)
RETURNING id, tour_package_id, image_url, created_at
`

type CreateTourImageParams struct {
	TourPackageID int64  `json:"tour_package_id"`
	ImageUrl      string `json:"image_url"`
}

func (q *Queries) CreateTourImage(ctx context.Context, arg CreateTourImageParams) (TourImage, error) {
	row := q.db.QueryRowContext(ctx, createTourImage, arg.TourPackageID, arg.ImageUrl)
	var i TourImage
	err := row.Scan(
		&i.ID,
		&i.TourPackageID,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createTourItinerary = `-- name: CreateTourItinerary :one
INSERT INTO tour_itineraries (tour_package_id, day_number, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tour_package_id, day_number, title, description, created_at
`

type CreateTourItineraryParams struct {
	TourPackageID int64  `json:"tour_package_id"`
	DayNumber     int32  `json:"day_number"`
	Title         string `json:"title"`
	Description   string `json:"description"`
}

func (q *Queries) CreateTourItinerary(ctx context.Context, arg CreateTourItineraryParams) (TourItinerary, error) {
	row := q.db.QueryRowContext(ctx, createTourItinerary,
		arg.TourPackageID,
		arg.DayNumber,
		arg.Title,
		arg.Description,
	)
	var i TourItinerary
	err := row.Scan(
		&i.ID,
		&i.TourPackageID,
		&i.DayNumber,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createTourPackage = `-- name: CreateTourPackage :one
INSERT INTO tour_packages (
  title, description, destination_id, price, duration_days,
  max_participants, min_participants, category, image_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, title, description, destination_id, price, duration_days, max_participants, min_participants, category, image_url, is_active, created_at, updated_at
`

type CreateTourPackageParams struct {
	Title           string `json:"title"`
	Description     string `json:"description"`
	DestinationID   int64  `json:"destination_id"`
	Price           string `json:"price"`
	DurationDays    int32  `json:"duration_days"`
	MaxParticipants int32  `json:"max_participants"`
	MinParticipants int32  `json:"min_participants"`
	Category        string `json:"category"`
	ImageUrl        string `json:"image_url"`
}

func (q *Queries) CreateTourPackage(ctx context.Context, arg CreateTourPackageParams) (TourPackage, error) {
	row := q.db.QueryRowContext(ctx, createTourPackage,
		arg.Title,
		arg.Description,
		arg.DestinationID,
		arg.Price,
		arg.DurationDays,
		arg.MaxParticipants,
		arg.MinParticipants,
		arg.Category,
		arg.ImageUrl,
	)
	var i TourPackage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DestinationID,
		&i.Price,
		&i.DurationDays,
		&i.MaxParticipants,
		&i.MinParticipants,
		&i.Category,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTourPackage = `-- name: DeleteTourPackage :exec
UPDATE tour_packages SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeleteTourPackage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTourPackage, id)
	return err
}

const getTourPackage = `-- name: GetTourPackage :one
SELECT id, title, description, destination_id, price, duration_days, max_participants, min_participants, category, image_url, is_active, created_at, updated_at FROM tour_packages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTourPackage(ctx context.Context, id int64) (TourPackage, error) {
	row := q.db.QueryRowContext(ctx, getTourPackage, id)
	var i TourPackage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DestinationID,
		&i.Price,
		&i.DurationDays,
		&i.MaxParticipants,
		&i.MinParticipants,
		&i.Category,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTourFacilities = `-- name: ListTourFacilities :many
SELECT id, tour_package_id, name, created_at FROM tour_facilities
WHERE tour_package_id = $1
ORDER BY name
`

func (q *Queries) ListTourFacilities(ctx context.Context, tourPackageID int64) ([]TourFacility, error) {
	rows, err := q.db.QueryContext(ctx, listTourFacilities, tourPackageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourFacility{}
	for rows.Next() {
		var i TourFacility
		if err := rows.Scan(
			&i.ID,
			&i.TourPackageID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTourImages = `-- name: ListTourImages :many
SELECT id, tour_package_id, image_url, created_at FROM tour_images
WHERE tour_package_id = $1
`

func (q *Queries) ListTourImages(ctx context.Context, tourPackageID int64) ([]TourImage, error) {
	rows, err := q.db.QueryContext(ctx, listTourImages, tourPackageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourImage{}
	for rows.Next() {
		var i TourImage
		if err := rows.Scan(
			&i.ID,
			&i.TourPackageID,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTourItineraries = `-- name: ListTourItineraries :many
SELECT id, tour_package_id, day_number, title, description, created_at FROM tour_itineraries
WHERE tour_package_id = $1
ORDER BY day_number
`

func (q *Queries) ListTourItineraries(ctx context.Context, tourPackageID int64) ([]TourItinerary, error) {
	rows, err := q.db.QueryContext(ctx, listTourItineraries, tourPackageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourItinerary{}
	for rows.Next() {
		var i TourItinerary
		if err := rows.Scan(
			&i.ID,
			&i.TourPackageID,
			&i.DayNumber,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTourPackages = `-- name: ListTourPackages :many
SELECT tp.id, tp.title, tp.description, tp.destination_id, tp.price, tp.duration_days, tp.max_participants, tp.min_participants, tp.category, tp.image_url, tp.is_active, tp.created_at, tp.updated_at FROM tour_packages tp
WHERE
  tp.is_active = true
  AND ($1::text = '' OR tp.title ILIKE '%' || $1 || '%' OR tp.description ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR tp.category = $2)
  AND ($3::bigint = 0 OR tp.destination_id = $3)
  AND ($4::decimal = 0 OR tp.price >= $4)
  AND ($5::decimal = 0 OR tp.price <= $5)
ORDER BY tp.created_at DESC
LIMIT $6 OFFSET $7
`

type ListTourPackagesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 int64  `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListTourPackages(ctx context.Context, arg ListTourPackagesParams) ([]TourPackage, error) {
	rows, err := q.db.QueryContext(ctx, listTourPackages,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TourPackage{}
	for rows.Next() {
		var i TourPackage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DestinationID,
			&i.Price,
			&i.DurationDays,
			&i.MaxParticipants,
			&i.MinParticipants,
			&i.Category,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTourPackage = `-- name: UpdateTourPackage :one
UPDATE tour_packages
SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  price = COALESCE($4, price),
  duration_days = COALESCE($5, duration_days),
  max_participants = COALESCE($6, max_participants),
  min_participants = COALESCE($7, min_participants),
  category = COALESCE($8, category),
  image_url = COALESCE($9, image_url),
  is_active = COALESCE($10, is_active),
  updated_at = now()
WHERE id = $1
RETURNING id, title, description, destination_id, price, duration_days, max_participants, min_participants, category, image_url, is_active, created_at, updated_at
`

type UpdateTourPackageParams struct {
	ID              int64          `json:"id"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	Price           sql.NullString `json:"price"`
	DurationDays    sql.NullInt32  `json:"duration_days"`
	MaxParticipants sql.NullInt32  `json:"max_participants"`
	MinParticipants sql.NullInt32  `json:"min_participants"`
	Category        sql.NullString `json:"category"`
	ImageUrl        sql.NullString `json:"image_url"`
	IsActive        sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateTourPackage(ctx context.Context, arg UpdateTourPackageParams) (TourPackage, error) {
	row := q.db.QueryRowContext(ctx, updateTourPackage,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.DurationDays,
		arg.MaxParticipants,
		arg.MinParticipants,
		arg.Category,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i TourPackage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DestinationID,
		&i.Price,
		&i.DurationDays,
		&i.MaxParticipants,
		&i.MinParticipants,
		&i.Category,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
